### ISSUE TITLE
Isotope not initialized in hidden tab/accordion

### ISSUE THREAD

**Issue by bravo14** [metafizzy/isotope#1048]
Hi

I am trying to us isotop inside a jquery ui accordion.  The layout doesn't initialize until I resize the screen and then change it back

The URL for this is http://217.199.187.196/wightwarriors.co/riders.php?riderId=1
`	<script>
$(document) .ready(function(){
$('.riderSponsorList').isotope({
  // options
  itemSelector: '.riderSponsorItem',
  layoutMode: 'masonry',
  masonry:{
	  isFitWidth: true
  }
});
});
</script>`

Do I need to do anything different for this?

**Comment by desandro** [comment]
Isotope needs to be triggered on a container & items that are visible. Isotope needs visible element in order to measure sizes and properly do layout.

In order to resolve this, you have two options:

+ Before initializing your accordion or tab widget, initialize Isotope first. Then initialize the widget.
+ When hidden content is revealed, trigger [`layout`](http://isotope.metafizzy.co/methods.html#layout) on it.

---

In your case, I recommend using this code:

``` js
$(function() {

  // init Isotope first
  $('.riderSponsorList').isotope({
    // options
    itemSelector: '.riderSponsorItem',
    layoutMode: 'masonry',
    masonry:{
      isFitWidth: true
    }
  });

  // init accordion
  $( "#accordion" ).accordion({
    active:false,
    collapsible:true,
    heightStyle:"content",
    // trigger Isotope layout
    activate: function( event, ui ){
      ui.newPanel.find('.riderSponsorList').isotope('layout');
    }
  });

});
```


And remove the other `.isotope()` init code.

**Comment by cburschka** [comment]
Note that even if the initialization is in the right order (so all tabs look good in the beginning), resizing the window will apparently trigger a layout change on the hidden tabs, and break the layout there.

In order to fix that, you probably *need* to rerun layout every time you change tabs - as in fact your suggested code does with the `activate` handler.
