### ISSUE TITLE
Adding with appended doesn't sort items

### ISSUE THREAD

**Issue by lukasfajger** [metafizzy/isotope#1053]
Hello!

I encountered a problem today with Vanilla JS Isotope. I tried to use updateSortData() function on my grid to update it but it seems it doesn't work.

However if I use jQuery it looks like it works. In other case it won't work if I use pure JS.

I did two example on codepen.io.

jQuery
http://codepen.io/anon/pen/bpdmJZ

Vanilla JS
http://codepen.io/anon/pen/oxXaJe

What is the problem?
What I want to do is simply to display grid and two buttons. I want to click in the button to sort by name. After that, I would like to click to load some of data to append it to the grid and automatically updateSortData. In jQuery it works as you can see in the above codepen links. In Vanilla JS it won't work.

Is it bug of isotope or am I doing something wrong?

I am not going to use any jQuery using Isotope cuz I prefer Vanilla JS and what I've also noticed is fact that you are using jquery functions in your methods which are devoted for pure js. For example makeArray() in this case in updateSortData function.

http://i.imgur.com/CUmXhd0.png

If I am wrong then I would like to apologize. :)

**Comment by desandro** [comment]
`appended` is useful if you're adding items to the end of the grid. If you want to add items WITH sorting applied, use [`insert`](http://isotope.metafizzy.co/methods.html#insert).

[See demo on CodePen](http://codepen.io/desandro/pen/06eb52bf986e6d9065e7af68a547f80c/)

You do not need to use `updateSortData` because the data (the text of `.post-title-name`) does not ever change.

The reason why they vanilla JS demo was different from the jQuery demo was because you were triggering `.isotope()` again in the jQuery demo.

**Comment by lukasfajger** [comment]
Hey @desandro !
You are completely right. Triggering isotope once again was misleading for me and I didn't notice I should use insert method instead of sortingData method.

Thank you for solving my issue so quick.
Isotope rox! :+1:
