### ISSUE TITLE
Still an issue with px gaps and % width

### ISSUE THREAD

**Issue by danyj** [metafizzy/isotope#1056]
I browsed the git
https://github.com/metafizzy/isotope/issues/671
https://github.com/metafizzy/isotope/issues/1054
https://github.com/metafizzy/isotope/issues/916#issuecomment-108899516
https://github.com/metafizzy/isotope/issues/684

and so on... for all possible solutions to this but the gaps are still there , 
the proposed  "fix" 

	width: 100.1%;
	width: calc( 100% + 1px );

does not work for me since I have item masks that overlap and become visible if I stretch the width 

![screenshot_8](https://cloud.githubusercontent.com/assets/2340172/13585901/93a5ea74-e4be-11e5-8a90-5383aedd0119.jpg)

If dont use those then I have the space 

![screenshot_7](https://cloud.githubusercontent.com/assets/2340172/13585874/6f9e0850-e4be-11e5-8772-112eee1da8fc.jpg)

if the space would be at the end of the 3rd column I would not bother , but it appears right in between them. 

Is there anything else you can suggest here? 

A px width calc on load and resize or anything that would fix this once and for all.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).

**Comment by danyj** [comment]
@desandro  bud , I have been your customer for couple years now , you know there is an issue , I posted reference with several git posts with same issue  and if you just type gaps in issue search you can see them https://github.com/metafizzy/isotope/search?q=gaps&type=Issues&utf8=%E2%9C%93

asking for test case when you know there is a bug is just going over the top or trying to make a fool out of someone. but here , have at it , those are your codepens and have same issues.  resize browser and you will either see a gap or overlap 


http://codepen.io/desandro/pen/NqpEbK

http://codepen.io/anon/pen/grrYpr

**Comment by danyj** [comment]
Here no border and I set the grid at crazy 997 max width which cant be divided properly as we know. 

http://codepen.io/anon/pen/Raabor

**Comment by desandro** [comment]
Thanks for that.

The same hack can be used. Add another element which can cover over the gap. [See demo on CodePen](http://codepen.io/desandro/pen/ca538fd8e2fbcb2416918099a6fcfdad/)

``` html
<div class="grid-item">
  <div class="grid-item-content"></div>
</div>
```

``` css
.grid-item-content {
  position: relative;
  width: 100.1%;
  width: calc( 100% + 1px );
  height: 100%;
  background: #09F;
}
```

---

Yes, I do recognize this issue is valid, but I don't know exactly what the issue is unless we are both looking at the same thing. Also consider someone else who comes across this issue.  That's why reduced test cases are so valuable.  My intention is to help you and me and everyone else understand the problem. I have no intention to make a fool out of anyone.

**Comment by danyj** [comment]
Look now , http://codepen.io/anon/pen/pyyyJd

that the issue that I have , I have a mask over and cant use either of those 2 gap/overlap hacks

**Comment by danyj** [comment]
Only reason why your pen looks ok is because everything is same color , but we both know that with images or items that have partially transparent masks there is now way that those 2 hacks can help.

**Comment by downFast** [comment]
@danyj I have worked out a mask over boxes with images and no gaps on another project using isotope, packery layout mode, bootstrap and some css, hope it helps www.exchangesvfx.com

**Comment by danyj** [comment]
@downFast  you did not fix it bud , you masked the bug with 1px padding and black bg , 

look now  with white bg , max width 937px and no 1px padding 

![screenshot_9](https://cloud.githubusercontent.com/assets/2340172/13615575/697a040c-e576-11e5-8044-a9e420b9704f.jpg)

I dont need a gap , otherwise I would find a solution , I need items to be next to eachother without gaps and with % width

**Comment by downFast** [comment]
Well my trick worked for me :)
I knew about the pixel issue with isotope. Maybe desandro should be left out fixing and building more important stuff while we find our tricks to fix personal problems. Is it not possible for you to add a negative margin to all boxes so that you will fix that px problem while loosing 1px from the other images? I think it would be acceptable and noone will ever notice it.

**Comment by danyj** [comment]
@downFast  this px gap is important to me and no I do not want or need hacks that just dont work. I dont see how me asking for support on a long time bug fix is taking away from desandros time and I sure dont see him complaining about me asking the question, so why you think I bother him is very questionable. And this is not  a personal problem as you see it but a computation bug. 

It is a bug that needs fixing and what worked for you does not work for me and others that had posted about it. 

Adding negative margin to all boxes does not fix it either since we dont know what box has a gap , so again no that does not work. As for no one noticing  , you can see the issue from the images I posted and it is very noticeable, especially when the gap/overlap is in the middle of the columns.

**Comment by downFast** [comment]
Just need to be a little more polite. A negative margin to all boxes not a single box, i said. Anyway it's a known bug.

**Comment by danyj** [comment]
@downFast  you the one who is rude by butting in where you dont belong and by hijacking my thread with your kiddy hacks and stupid remarks. So please stay out of this and stop pushing it.

**Comment by desandro** [comment]
I don't think we're going to find a suitable solution. Isotope does have this 1px bug. There are hacks to address it, but they are hacks. None of them are perfect. To truly resolve this issue, consider larger changes: are the masks necessary? Or maybe Isotope is not the right choice for this project.

I'm closing and locking this issue because your words are curt.
