### ISSUE TITLE
button-group problem with initial filter

### ISSUE THREAD

**Issue by permss** [metafizzy/isotope#1083]
Hi - thanks a lot for this great work, i like it!!

I've a problem with setting an initial filter... please take a look at http://codepen.io/perms/pen/jqvrbo

Initial I set the filter to "South Africa", "windows" and "monthly" - this works fine. But: when i click on a button (for example "linux") everything with datafilter "linux" is shown. The initial filter "south africa" and "monthly" will reset. You will see my problem at codepen; it's a bit difficult to descripe ;-)

So is it possible to set initial filter for all button-groups and save them?
Sorry for my bad english!!

**Comment by desandro** [comment]
Thanks for reporting this issue. You may have filtered the items in Isotope, but you'll need to update the internal variable `filters` in order to preserve the state. You can even get initial data from HTML, rather than hard-coding it in HTML.  See demo http://codepen.io/desandro/pen/20ad6a0c9b1e19164cc459fca11d6d0a/


``` js
// build initial filter
var $filters = $('.filters');

$filters.find('.button-group').each( function( i, buttonGroup ) {
  var $buttonGroup = $( buttonGroup );
  var filterGroup = $buttonGroup.attr('data-filter-group');
  var filter = $buttonGroup.find('.button.is-checked').attr('data-filter');
  if ( filter ) {
    filters[ filterGroup ] = filter;
  }
});

// init Isotope
var $grid = $('.grid').isotope({
  itemSelector: '.server-select',
  filter: concatValues( filters )
});
```
