### ISSUE TITLE
Using multiple filters with URL Hash

### ISSUE THREAD

**Issue by NickHeurter** [metafizzy/isotope#1114]
Hi @desandro, is it possible to use multiple filters in combination with the URL hash in the latest version of Isotope? 

I already used [your CodePen ](https://codepen.io/desandro/pen/vErxXj/) for my current filter and I'm known with [your example](http://isotope.metafizzy.co/v1/demos/hash-history.html) in Isotope v1 on how to fix this. I want the output of your example in Isotope v1, but then with Isotope v2. Is this possible?

I want multiple filters with their own URL Hash. So I would like to get the following URL structure: `http://website.com/#filter_1=.red&filter_2=square` which should result in the following filter: `$grid.isotope({ filter: '.transition,.square' })`

Already thanks for your help!

**Comment by desandro** [comment]
Here you go, the nastiest Isotope demo I ever made: http://isotope.metafizzy.co/v1/tests/combo-sort-history.html

**Warning**

This demo was created years ago. Since then, I feel that this behavior — mixing hash history with combination filters with UI elements — is too complex. For all the work that goes into it, it does not provide that much benefit for your users. I recommend dropping the hash history feature all together.
