### ISSUE TITLE
Items all display:none when isotope initializes

### ISSUE THREAD

**Issue by narutoniue** [metafizzy/isotope#1115]
I'm not sure what is going on, as isotope was working earlier for me, but now doesn't.

All items are not showing up.  However, if you click all, they do, but the container they are contained in is not being updated for the proper height.  I have no idea why this is happening.

Test case: http://codepen.io/anon/pen/pbyypz

**Comment by desandro** [comment]
Thanks for the test case. I believe the issue was how you were using different variables for `$gridStore`. Looks like you can resolve this by using the same variable. See demo http://codepen.io/desandro/pen/c061dec46a3155d1cd19d2a039e297bb/

Also, [$(window).load is a last resort](http://metafizzy.co/blog/window-load-last-resort/).

**Comment by narutoniue** [comment]
So I fixed the var issue, however, if I click on a filter, it only hides the ones not in that class, and doesn't reposition them.  So all the items still keep their same left/top value, but are either display:none or viewable.

Regarding the window.load, I tried moving it into doc ready, but then the filter buttons didn't work - they didn't fire when I clicked on them.

**Comment by desandro** [comment]
Sorry, but I won't be able to debug this issue.
