### ISSUE TITLE
Combination inclusive and exclusive: How can I use <ul> instead <select>?

### ISSUE THREAD

**Issue by nykka** [metafizzy/isotope#1151]
I'm using this extra http://codepen.io/desandro/pen/GFbAs and it works like a charm.
But I want to use an **ul** element (instead of **select**). Is it that possible?
Thanks!

**Comment by thesublimeobject** [comment]
@desandro ... I've done this like a million times, would it be helpful if I wrote out an example of some sort for you to use?

**Comment by desandro** [comment]
@thesublimeobject That'd be great! A simplified CodePen would be most helpful.

**Comment by thesublimeobject** [comment]
@desandro Okay, cool. I'll try to get it done over the weekend.

**Comment by thesublimeobject** [comment]
@desandro Does this work okay?—http://codepen.io/thesublimeobjekt/pen/ZLoZEG

I have a lot of boilerplate around these because I've been building them forever, so I tried to simplify it as much as I could.

The source code is [here](https://github.com/thesublimeobject/isotope--demo), which is a little easier to follow, I think. But I can simplify it a little more if it would be helpful!

**Comment by desandro** [comment]
Thank you!
