### ISSUE TITLE
Other page items jump when isotope filters

### ISSUE THREAD

**Issue by tgreen7** [metafizzy/isotope#1153]
Filtering makes other items on page jump without, not the smooth animation that isotope offers. Smooth realignment should be there by default.

**Test case:** http://codepen.io/tgreen/full/PzAYWv/

**Comment by desandro** [comment]
Thanks for reporting this issue. This behavior is intended. When you filter, Isotope changes the height of the container element. Changing height is a paint trigger. It causes the browser to re-render the entire page. The change is instant rather than transitioned to keep browser performance up.

If you still prefer to transition height, you can do so with CSS.

``` css
.grid {
  transition: height 0.4s;
}
```

See demo  http://codepen.io/desandro/pen/8995ffa7563d2d57d6fb5f92e607bfe5/

**Comment by tgreen7** [comment]
Thanks so much!
