### ISSUE TITLE
No layout mode: packery

### ISSUE THREAD

**Issue by demiantriebl** [metafizzy/isotope#1175]
i use Isotope for meteor and i try to use packery layout but says its not supported

 **Uncaught Error: No layout mode: packery**

its this function on meteor isotope?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

Have you added [packery-mode.js](http://isotope.metafizzy.co/layout-modes/packery.html#install) ?

**Comment by demiantriebl** [comment]
yes i install with npm 

npm install isotope-packery

but don't working, i try to submit the reduced test case, but i think the problem is in the package isotope:isotope of meteor. thanks

**Comment by HectorRPL** [comment]
Hello, yeah, I have the same issue.
I have a template with  `isotope.pkgd.min.js` and `packery-mode.pkgd.min.js` files. I can't importthe `.js` files like a module in meteor because the console send me the next error:

> Uncaught Error: Cannot find module 'jquery'

So, I try the install with Admosphere, but other issue appear:

> Uncaught Error: No layout mode: packery

And the template don't show the elements. Any Ideas?
Thanks for read

**Comment by HectorRPL** [comment]
One more thing. 
My problem is not with Isotope, the problem is the way that the files load, because I have this post in stackoverflow. In my aplication exist a momento where all is perfect, isotope works fine and no errors, please give a check to my post

[stackoverflow](http://stackoverflow.com/questions/40026970/i-cant-integrate-a-web-template-purchased-into-meteor/40029795#40029795)

**Comment by metaskills** [comment]
I used the dist/packaged version and got this error. Might help if the docs mentioned this.

**Comment by desandro** [comment]
@metaskills Did the [documentation on the Packery layout mode page](https://isotope.metafizzy.co/layout-modes/packery.html#install) not catch your issue?

**Comment by metaskills** [comment]
Ugh... classic, I just had an OS issue where someone missed my docs too. And no, I did not see that one :) thanks!!!

**Comment by smeisinger** [comment]
So which version are we supposed to use? It doesn’t matter which one I use, I always get this error.

Using packery without Isotope works perfect, but it doesn’t work with Isotope.

Sorry, but I just don’t get this information from the documentation page. The logical thing to do would be to just use the version there (I don’t use bower or npm).

**Comment by smeisinger** [comment]
Solved it.

I didn't download the files from the documentation, I just opened them and copy&pasted the code into a new JS file on my server.

For whatever reason I had this at the end of my JS file then:

> 0
> Viewport
> Window
> ×
> ×
> ×

I saw that earlier, but I didn't take it seriously as I though Packery just gives me pointless error for no reason …

Layer 8 problem.
