### ISSUE TITLE
Disable combination of filters with no result

### ISSUE THREAD

**Issue by derburner23** [metafizzy/isotope#1184]
Hi there,
is there any easy way to disable combinations of filters with no results so that they can't be clicked? Please visit [this example](http://everyonelovessharing.com/misc/isotopedemo/) to see what i mean. The examples works great but the jQuery behind it is way too complex since it contains code for all possible cases (see [here](http://everyonelovessharing.com/misc/isotope.combofilter.js)). Thanks for the great work!

**Comment by desandro** [comment]
Sorry, I won't be able to provide personal support for this issue.

I do see you're using Isotope v1. I recommend upgrading to the latest [Isotope v3](http://isotope.metafizzy.co). You may find the combination filter code easier in the newer example: http://isotope.metafizzy.co/filtering.html#combination-filters

**Comment by thesublimeobject** [comment]
@derburner23 This isn't the most efficient solution in the world, but this is a pretty easy one, if you're interested:

```
var currentFilters = $('.grid').find(filters)
if (currentFilters.length === 1) {
    $('.grid').append('<p>Sorry, your search returned no results. Please try again.')
}
```

I added this to the codepen from the page @desandro linked right before the Isotope filter method. It basically just runs a search on nodes the have the classes of whatever the filter combination is. Because that all of the combos in the example actually have an instance, I set the length equal to 1, but in a real world case you would want to set it to 0, of course.  

If this is the case, instead of not being able to click it, you can just append a note that the search did not return any results, which in my mind is actually a better user experience that not allowing the user to click it (often this leads the user to think the functionality might be broken, which can be frustrating). If you are to use this, I would just be sure and write a method to remove the node on a successful search as well. Or, to be thorough, it would probably be even better just to keep a hidden node that you can change the class on from something like `.hidden` to `.visible`, or whatever you would like.

Hope this is helpful!
