### ISSUE TITLE
allow init with hidden items by treating display:none items as hidden

### ISSUE THREAD

**Issue by pkundrat** [metafizzy/isotope#1195]
I find it a bit disturbing to look at the mess of stacked tiles before they are laid out - and this is usually quite long until all the dependency scripts are loaded. When trying to start with all items hidden (via display:none) isotope doesnt consider them hidden so there is no need to reveal them - this gets in sync when all items have their isHidden flag toggled.
I can work around the problem by setting visibility: hidden before the layout and clear afterwards, but cleanest solution would be if Isotope set isHidden for items which have display: none.
I can even provide fix if the solution is accepted.

**Comment by thesublimeobject** [comment]
@pkundrat There are actually a lot of pretty easy solutions to this, if I understand you correctly. Often times I'll just have a simple set of CSS rules on the items, which lay them out identically to how they will be laid out in Isotope, and then pop a `isotope--loaded` class onto the container when it's ready. Now, I will concede, this solution only really works when the items are basically the same size or in ratio to each other in a fairly simple way. 

If you have a more complex layout you may consider not actually instantiating the Isotope() instance until your scripts have loaded, and then manually append an array of DOMElements to the instance. 

I don't know. Just trying to help here. I have probably used like 15 different methods to avoid what you're talking about because the head of our design firm really hate when it does that haha.

**Comment by pkundrat** [comment]
@thesublimeobject  Haha - he didnt like the first 14 approaches? :) 
As i mentioned - i solved the problem by playing with visibility - i was just proposing cleaner solution - Isotope synced its internal state with actual visibility. I will submit the fix - hopefully it will be a one liner.

**Comment by thesublimeobject** [comment]
@pkundrat cool. just figured i'd be helpful just in case. ;)

**Comment by Surt** [comment]
Hi @pkundrat 
I know, it has been a long time, but could you share the solution?

**Comment by thesublimeobject** [comment]
@Surt can you be more specific about what you're looking for? just a solution to isotope looking messy when it's first loaded?

**Comment by Surt** [comment]
yep, I wanted to show the options with the "ordering" animation at first.
I'm actually hiding the grid, then waiting for the first load to finish and then showing the grid again with everything loaded. No animation since I couldn't make it looks ok. 

https://tympanus.net/Development/GridLoadingAnimations/
If you click on an option on the right you will see the elements appear with the animation. Thats what I'm looking at the start, when page finish loading.

**Comment by desandro** [comment]
See demo https://codepen.io/desandro/pen/bsHix and discussion https://github.com/desandro/masonry/issues/501
