### ISSUE TITLE
Gutter doubles when items have varying sizes.

### ISSUE THREAD

**Issue by d3haynes** [metafizzy/isotope#1212]
test case: http://codepen.io/idevelopweb/pen/MJvzeE

using masonry and percentage base, if I use a gutter - anytime an element larger than the item used for sizing, or the first item if not specified, my gutter doubles. you can see this in the example. I have tried a combination of different things, including using imagesLoaded. the only conclusion I can come to is that its doubling the column width (set in the options by the first item) and that makes it double the gutter.

**Comment by thesublimeobject** [comment]
@d3haynes See an updated pen I made here: http://codepen.io/thesublimeobjekt/pen/wgPKoB

Now, this is a little rough and I had to mess with your structure a bit, but this is how I write a lot of my Isotope instances. There are two mains things here:

1. The structure of your inner content was really messing with the sizing of each item. Most of the times it's much better to set a specific height on the items unless you know for sure that all your images are the exact same ratio/height, which they weren't. In addition, you were applying "height: 100%" to some elements which didn't actually have a height set on their parent container. That CSS query ("height: 100%") only works well when the parent has an explicit height; this in turn was throwing the height of everything off a little bit.

1 (a). A sub-point here, I've actually removed your links for now. In my years as a developer I've found it very problematic to try and mess with styles a link that's wrapping a lot of complexly styled content. If I were you, I would just put the link on the outer most div:

```
<div class="project">
    <a href="">
    <div class="all-the-other-stuff-in-here"></div>
</div>
```

Then style the link as:

```
.link {
    display: block;
    width: 100%;
    height: 100%;
    position: absolute;
    left: 0;
    top: 0;
}
```

So, we end up getting a link that covers the entire surface, it's events bubble to project, so in cases like this you still get all the goodness of just using `.project:hover .whatever`, and we don't have any styling weirdness messing with the sizing of our items.

2. I personally tend to extend most of my isotope grids all the way across the page. There honestly may be better built-in ways to do this now, but I've been using it for a long time so I _always_ subtract the width of the gutter inside the CSS query for my width. That translates to this SASS formula (which should be easily translatable even if you don't really know SASS, I think):

```
@function width($rows, $margin) {
	$width: 100% / $rows;
	$margin: $margin * (($rows - 1) / $rows);
	@return calc(#{$width} - #{$margin});
}
```

Thus, for something like .project, instead of just `width: 20%`, you end up with `width: calc(20% - (10px * 3 / 4))`, and for the wider item, `width: calc(40% - (10px * 1 / 2))`. The reasoning behind this is that you are basically subtracting out the width for each column of gutter, therefore balancing the width of each regular column/item.

Anyway, the pen seems to work as you wanted now, please let me know if you have any questions and I am happy to help further.

**Comment by d3haynes** [comment]
@thesublimeobject thanks for the response man! A few things:

1. the height: 100% I use is on the anchor element and then below that on the content element, which is positioned absolutely - I want it to use all of the height of its parent. Since the outermost element (.project) has a height set, this applies properly, no?

2. My anchor does wrap all of my nested content, as its the first child element of .project, I'm curious what part of that was causing an issue specifically. 

3. I see your pen solves that odd gutter offset after the width of the elements change, but still does not place the fourth item in the row at the top right, instead kicking it to the next line. I used LESS on this project, and my widths set as 

`&.regular {
    	width: calc(~"20% - (10px * 3 / 4)");
    }
    &.wide {
    	width: calc(~"40% - (10px * 3 / 4)");
    }
    &.wide_tall {
    	width: calc(~"40% - (10px * 3 / 4)");
    }
`
I can tweak that so the rows have 4 items, but again the gutters become a problem. Even if I set the same width and height for all elements, it still does not fill the full width of the container. 

I appreciate the insight and time!

**Comment by d3haynes** [comment]
Another thing to note:

if I make them all the same width, this problem obviously goes away. as it stands, once it sees the item that is wider than the rest, it still adds in about 2px of extra space, which is kicking down that last item.

**Comment by desandro** [comment]
@thesublimeobject thanks again for your input. Can you please email me yo@metafizzy.co so I can properly thank you?

**Comment by thesublimeobject** [comment]
@desandro Email sent :)
