### ISSUE TITLE
Side push off canvas menu is breaking the masonry layout

### ISSUE THREAD

**Issue by jorge52970** [metafizzy/isotope#1213]
I am implementing a "side push off canvas" menu like this one:

http://www.w3schools.com/howto/howto_js_sidenav.asp

Each time that I open the menu the masonry layout gets broken, see screen captures:

Before:

![screen shot 2017-01-26 at 12 06 55 pm](https://cloud.githubusercontent.com/assets/5608493/22344039/0aef67b2-e3c0-11e6-8ff1-436b68839695.png)

After:

![screen shot 2017-01-26 at 12 07 12 pm](https://cloud.githubusercontent.com/assets/5608493/22344038/0aef2d60-e3c0-11e6-9015-79ec7a72f76e.png)

 Any idea how to address this problem?

**Comment by thesublimeobject** [comment]
@jorge52970 

You would need to show more of your code here, or a full example, but I am going to assume what is occurring is that when you're menu is changing the size of your isotope container, the container and the elements within it are either trying to resize, and are not set up to resize properly, or resize is turned off, which is probably jamming them to an extent (honestly, I'm extrapolating a bit here because I've literally never turned `resize` off before). 

So essentially, this could depend on a lot of things: whether you have your columns set in percentages or fixed widths, whether `resize` is set to true, other CSS props, etc. Nonetheless, the root of your problem is definitely that by pushing the menu _into_ the screen you are transforming the size of the Isotope container, and therefore changing the column structure, possibly the item size, etc.

If you would like to post a more specific example I would be happy to be more specific.

**Comment by jorge52970** [comment]
Thank you for your response, here is the project code:

https://jsfiddle.net/zrhaaL4r/

**Comment by thesublimeobject** [comment]
Is there any reason you're using v1? Also, you have `.item` as columnWidth, but `.item` has no CSS selector.

**Comment by desandro** [comment]
Sorry, but we won't be able to debug this issue.
