### ISSUE TITLE
Masonry not working instantly after ajax call

### ISSUE THREAD

**Issue by fen89** [metafizzy/isotope#1262]
**Test case:** https://codepen.io/anon/pen/XRxrwK

Hey,

I encountered a problem when I am trying to load another page via jQuery.load() into the current one. I am not able to get isotope working correctly.

On my local project I am trying to display a modal which loads the images container from another page and displays it, which works fine, but Isotope is not working for this images-container, until I change the size of the browser.

After loading and displaying the modal: Images are stacked, isotope has done nothing.
![isotope-1](https://cloud.githubusercontent.com/assets/4036376/26207467/e656c53c-3be7-11e7-91ad-093bc895f952.png)

After browser resize, isotope started working:
![isotope-2](https://cloud.githubusercontent.com/assets/4036376/26207510/035feb72-3be8-11e7-9c64-c55cd5bf87f3.png)

Any help on this problem?
Thanks!

**Comment by desandro** [comment]
Thanks for reporting this issue. With jQuery `load`, the complete callback function provides the `responseText` as an argument

``` js
// doesn't work
$('.container').load( url, function( response ) {
  var $grid = $( response ).find('.grid');
  $grid.isotope({
    // ...
  });
});
```

The `responseText` is inserted into the HTML before the callback is called. But `responseText` is just text, it's separate from the HTML that has been inserted.

The fix is to find the elements that have been inserted in the HTML, and use that for initialization

``` js
// works
var $container $('.container').load( url, function( response ) {
  // get grid loaded in container
  var $grid = $container.find('.grid');
  $grid.isotope({
    // ...
  });
});
```

See demo https://codepen.io/desandro/pen/ca6387bb93fc345c5f95aef3d12fa52a
