### ISSUE TITLE
Isotope not resizing with an accordion

### ISSUE THREAD

**Issue by fredhigsonbrown** [metafizzy/isotope#1285]
Hi! I'm having issues when trying to resize the grid when using an accordion. 

It seems to be almost working backwards so when the accordion title is clicked and the content displays then the grid closes up rather than expanding.

https://codepen.io/fredkonstrkt/pen/eRWpJa

Any help appreciated!

**Comment by desandro** [comment]
Thanks for reporting this issue. The trouble is that Isotope needs items to have their size set in order to layout them out. In this case, that means waiting for the slideUp/slideDown animation to finish before triggering `layout`.  You can do this as part of the slideUp/slideDown callback:

``` js
$grid.on( 'click', '.accordion-title', function( event ) {
  var $title = $( event.currentTarget );
  var $colourItem = $title.parents('.colour-item');
  // close other accordion
  $grid.find('.is-accordion-open').removeClass('is-accordion-open')
    .find('.accordion-content').slideUp( 'normal', layoutIsotope );
  $colourItem.toggleClass('is-accordion-open');
  var isOpen = $colourItem.hasClass('is-accordion-open');
  if ( isOpen ) {
    $colourItem.find('.accordion-content').slideDown('normal', layoutIsotope );
  }
});

function layoutIsotope() {
  $grid.isotope('layout');
}
```

See demo https://codepen.io/desandro/pen/66d463cc6c49b75a2e1a638043076e56/

**Comment by nosgihderf** [comment]
Thanks Desandro! I'll implement this, one thing I can see it's doing is not closing the accordion, the only way to close that would be to open another. 

Thanks again!

**Comment by desandro** [comment]
> one thing I can see it's doing is not closing the accordion, the only way to close that would be to open another.

Ah sorry about that. Fixed!

**Comment by nosgihderf** [comment]
That's perfect! Thanks buddy!

**Comment by paulhaem** [comment]
Hello,
I've got quite a similar problem. I am using the "filtering with search field" to filter some Bootstrap collapse. When I open it it should push down the other grid items, as it is a child of the grid-item (mentioned here: https://isotope.metafizzy.co/extras.html#animating-item-size). But it is just overlapping the grid-items below. As it is no image or font I cannot use imagesLoaded. After 'layout' is called (e.g. window resize, or manual) the grid-items align itself below the content, but sticks there after collapse.

https://codepen.io/paulhaem/pen/ZJELJr/

I really would like to avoid using triggers. Any ideas? :-/

**Comment by desandro** [comment]
You'll need to trigger Isotope [layout](https://isotope.metafizzy.co/methods.html#layout) on [Bootstrap's collapse events](http://getbootstrap.com/javascript/#collapse-events) 

See demo https://codepen.io/desandro/pen/89eff71338ed450ff59bec828f7a9772/

**Comment by paulhaem** [comment]
Thanks for the answer and the demo! :+1: 

But what about animating the size with childs? Isn't it possible to push down the other grid-items along with the growing size of the grid-item on top for a smooth animation?

**Comment by desandro** [comment]
> Isn't it possible to push down the other grid-items along with the growing size of the grid-item on top for a smooth animation?

Yes, it's possible under certain conditions. The [animating size demos](https://isotope.metafizzy.co/extras.html#animating-item-size) work because the expanded items have a set size. So an outer element is immediately changed to that size, while the inner element is transitioned to the expanded size.

Your demo has text, which varies the height of the item. So it's not quite possible. But you could hack it by using a fixed size for expanded items. I recommend you dig into the animating size demos and try building your own solution.

**Comment by paulhaem** [comment]
@desandro: This demo is not working properly with Internet Explorer 11. The grid-items are positioned half on top of each others.
