### ISSUE TITLE
isotope.remove(--all--) + addItems(--all--) has unexpected behavior

### ISSUE THREAD

**Issue by pakx** [metafizzy/isotope#1295]
I'm looking to use isotope with a vdom-based ui library -- specifically, Mithril. In looking into different isotope "refresh strategies" I see unexpected behavior.

BACKGROUND:

As I understand it, isotope/container relationship has the following aspects
- container contains items
- isotope has an internal collection of item references

Thus isotope refresh strategies I could use when adding/removing items from container are:
a) reload: isotope.reloadItems() + .arrange()
b) add/remove: .addItems() + .remove() + .arrange(), as items are added/removed
c) re-create: remove all items from isotope, then re-add all items to isotope

Option (c) looks like it should work, but it doesn't. Pls would you comment why?

Here's a plain-javascript sample: https://goo.gl/7p6Aeu (has some setup boilerplate, sorry)

Thx!

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue.

First off, Isotope was not designed with virtual DOM frameworks in mind. You'll likely run into multiple issues using Isotope with a V-DOM because they have conflicting behaviors manipulating the DOM.

On top of that [Isotope's `remove` method](https://isotope.metafizzy.co/methods.html#remove) was designed for removing a couple items. Not for reloading all active items. [`reloadItems`](https://isotope.metafizzy.co/methods.html#reloaditems) may be a better solution. Or you can [`destroy`](https://isotope.metafizzy.co/methods.html#destroy) and initialize a new instance.

Could you try forking this example, so I have a better idea of what you're trying to do? https://codepen.io/desandro/pen/7361027b1df1b1618846b76319524a9d

**Comment by pakx** [comment]
David, I don't see a "Fork" button on the pen that comes up at that link. I thought maybe one needs to have an account, so created one and still no "Fork" button -- top-bar buttons are "Settings", "Change View", "Log In", "Sign Up".

I haven't used codepen; perhaps I'm missing something? (usage videos I just now looked up all show a Fork button, so dunno why I don't see one. On both FF & Chrome.)

**Comment by desandro** [comment]
I've made the pen public https://codepen.io/desandro/pen/NvKbdW/

**Comment by pakx** [comment]
David,

Hhhh, my mistake -- I thought iso.remove() removed only from isotope; I now notice/read it removes from DOM as well (as counterpart to insert())

Apologies. Pls close.

Related, though:
- is there a method to remove an item from isotope only (i.e. not from DOM)?
- does metafizze have gitter or slack channels, or other discussion area?

Thx again!

**Comment by desandro** [comment]
Thanks for following up!

> is there a method to remove an item from isotope only (i.e. not from DOM)?

Sorry no, but you could add your own method `itemRemove`:

``` js
Isotope.prototype.itemRemove = function( elems ) {
  var removeItems = this.getItems( elems );
  fizzyUIUtils.removeFrom( this.items, item );
};
```

> does metafizze have gitter or slack channels, or other discussion area?

Sorry nope. I've found that I'm easily distracted by Slack (etc.) and it would pull away from actively working on Metafizzy.

**Comment by pakx** [comment]
Thanx, David. Take care.
