### ISSUE TITLE
IE11: wrong positioning

### ISSUE THREAD

**Issue by paulhaem** [metafizzy/isotope#1311]
Your [demo](https://codepen.io/desandro/pen/89eff71338ed450ff59bec828f7a9772/) does work properly with Edge, Firefox and Chrome but not with IE11. Since IE11 is the newest IE version and some Windows 7 users still have to use it instead of Edge it should be included in the support.

The position of each grid-item is reduced to the half of each grid-item on top of it.

Demo from: https://github.com/metafizzy/isotope/issues/1285

**Comment by desandro** [comment]
Thanks for reporting this issue. That CodePen was a support request I was able to fulfill for another user, not quite an official demo. it mixes jQuery animation with Isotope, which I do not recommend. If you do have a **reduced test case** demonstrating a layout problem with isotope in IE11, i can take a look. Otherwise, I consider this a user-side bug.
