### ISSUE TITLE
jumping animations on filtering

### ISSUE THREAD

**Issue by MADAMEquirin** [metafizzy/isotope#1395]
hi desandro

sorry for bothering! i updated our website to V2 and have the jumping issue. i cut all the css transition parts without success. any tip what else to look for?

you can see it here: http://blog.madame.at/projects/

best,
Q

**Test case:** https://codepen.io/desandro/pen/mEinp

**Comment by desandro** [comment]
Thanks for reporting this issue. Hmm, the problem may be in how you're setting `hiddenStyle`. If you wish to hide/reveal items with only opacity, you should set:

``` js
$('.grid').isotope({
  hiddenStyle: { opacity: 0 },
  visibleStyle: { opacity: 1 },
});
```

I believe the issue is that Isotope is expecting the transition for `transform` to complete, but because `scale(1)` never changes it does not complete.

**Comment by MADAMEquirin** [comment]
perfect - thx!
