### ISSUE TITLE
Isotope breaks bootstrap order

### ISSUE THREAD

**Issue by vitorregisrr** [metafizzy/isotope#1416]
**Test case:** https://codepen.io/desandro/pen/mEinp

Can you guys fix it? When we have a bootstrap row with the isotope grid, we can't use the flexbox ordering!

(poor) Into this code for example, the order doesn't work because of isotope's grid.
![image](https://user-images.githubusercontent.com/9900252/41566358-96c9d07c-7331-11e8-959a-979a61c04f9e.png)

**Comment by downFast** [comment]
May I ask you why you're using Figure? And also, what is the desired result, I'm not too sure what's your goal in using bootstrap ordering and isotope

**Comment by magicwatchs** [comment]
![image](https://user-images.githubusercontent.com/9900252/41567692-d9789f60-7337-11e8-99b1-62c46813ef5c.png)
The cards with the badges "Liberado" and "Solicitado" must come first than the card with "Bloqueado" when you are seing all the filters, so, to do this, i need to use the flexbox order.
I'm sure the problem is between flexbox and isotope integration, beucase when I pull out the isotope from the code, the ordering works correctly.
I am using the figure for semantic issues.

**Comment by magicwatchs** [comment]
am i using the figure wrong?

**Comment by downFast** [comment]
Ok figure.. bootstrap doesn't use figure and it isn't needed there for sematich, that why I've asked, see: https://getbootstrap.com/docs/4.1/components/card/#card-decks

The in regards of the order, if the boxes are the same sizes, then the html order isn't touched by isotope, so you won't need to use any bootstrap ordering, just move the html and place them at the start.

In case for whatever other reasons you'd need to place these at the top, then you could have a look at stamp https://isotope.metafizzy.co/options.html#stamp

or even sort could help 1. sort https://isotope.metafizzy.co/sorting.html
