### ISSUE TITLE
Isotope Combination filtering with Checkboxes

### ISSUE THREAD

**Issue by zegermens** [metafizzy/isotope#143]
Hello. I purchased a support licence a while back but realise you have stopped the service, I've searched the internet high and low and still cannot find anyway to get this working. I was wondering whether someone can help me with an issue I'm having. I'm creating an online store and plan to use Isotope to display products. I will have a navigation using check boxes so the customer can then filter between brand, product type and a couple of other options.

I have so far managed to get it to work using drop down menu's but every time i use a check box it will not work at all. The masonry layout I'm using reverts back to a standard layout and nothing will filter.

I have recreated in JSfiddle what I've got so far. http://jsfiddle.net/zegermens/2aHXN/

There is also one other thing that I'm also not 100% sure how to implement. I would like it if there are no products that match the filtered options is there anyway i can show a message or another div where i can have a message saying nothing found?

Any help with this would be superb!

Thanks

**Comment by mwellman-rm** [comment]
@desandro Shooting in the dark here but how could we modify the code so that the filtering is subtractive instead of additive?  So for example if I was going to select Brand 1 and Brand 2; nothing would show.  To be clearer if I was going to select Brand 1, Type 1, Red and Blue; "item brand1 type1 red uk-size11" would not show since it doesn't contain blue.

**Comment by mwellman-rm** [comment]
I figured it out.  Lack of sleep, ha.
