### ISSUE TITLE
Bug associated with sorting? "o is not a function"

### ISSUE THREAD

**Issue by geigel** [metafizzy/isotope#1476]
I think there's an error with some of the code related to sorting:

On this line in the min file:

`{var o=e[i];this.sortData[i]=o(this.element,this)}}`

I needed to change the "e[i]" to "t[i]" for it to work. 

I kept getting this error in console: https://snag.gy/VOQql1.jpg

Here's the code I was executing that caused the error: https://snag.gy/kUXzeb.jpg

Don't know anymore info I can provide of help except what I've given above.

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope. Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/.github/contributing.md#submitting-issues).

**Comment by snwokenk** [comment]
Had the same issue. solved by using updateSortData

I was getting extra html data from the server and loading it to div1, then doing something like:
`var $content = $($div1.html());
setTimeout( function () {
                                $grid.append($content);
                                $grid.isotope('appended', $content);
                            }, 500);`
On new windows I would get the error but if i refreshed or reloaded the window the error would not appear and layout would work properly.

what solved the issue was adding
`$grid.isotope('updateSortData', $content);`

so my code looked like this:
`var $content = $($div1.html());
setTimeout( function () {
                                $grid.append($content);
                                $grid.isotope('updateSortData', $content);
                                $grid.isotope('appended', $content);
                            }, 500);`

**Comment by geigel** [comment]
I'm glad you found a work-around. I am still running the modified version of the min code that I did above and it works. IMO it's definitely a bug with the code though. Glad I'm not the only one who ran into the issue.
