### ISSUE TITLE
npm ERR! Refusing to install package with name "isotope-layout" under a package

### ISSUE THREAD

**Issue by laendle** [metafizzy/isotope#1548]
Windows 10 x64

```
D:\isotope>npm --version
6.14.5
```

```
D:\isotope>git show-ref --heads -s
1dd4cd186a599dfd70846431506437fe774c285e
```

```
D:\isotope>npm install isotope-layout --save
npm ERR! code ENOSELF
npm ERR! Refusing to install package with name "isotope-layout" under a package
npm ERR! also called "isotope-layout". Did you name your project the same
npm ERR! as the dependency you're installing?
```

Hello, 

With the latest pull from the repo, `npm` fails, am I missing something that is not documented on the project home page ?

**Comment by thesublimeobject** [comment]
@splattadat do you have a package.json in the directory the you're currently trying to install the isotope-layout package? and if so, does it have a `"name": "isotope-layout"` property? that seems to be what the error is indicating, but if that's not the case, i may need more information in order to help.
