### ISSUE TITLE
Grid not working anymore in chrome85

### ISSUE THREAD

**Issue by nattyluke** [metafizzy/isotope#1558]
Hej did you see that the grid system is not working anymore in chrome85? In version 84 no problem.
In version 85 everything gets aligned vertical.

**Comment by thesublimeobject** [comment]
@nattyluke do you have a more specific example of this bug? i have several implementations across different sites, and they all look normal in chrome v85. it's possible that there is a bug related to that version, but it may be something more specific that i would need more context in order to help.

**Comment by nattyluke** [comment]
We could solve it, inside our grid elements there was an image with _width="100%"_ which destroyed the layout... Somehow chrome got stricter interpreting the code
