### ISSUE TITLE
isotope not initialized. Cannot call methods, i.e. $().isotope("layout")

### ISSUE THREAD

**Issue by hayleyhailstorm** [metafizzy/isotope#1561]
Hi -
I'm trying to use the Advanced Tabs (part of Elementor Essential Add-ons) and whenever I click the second or third tab, the items become displaced and shift so they're cut off on the right-side. 

This is the link to the page I'm referring to: [Our Services](http://retheme20.eppley.org/our-services/); I also attached a screenshot.

Any help would be greatly appreciated.
![our-services-tabs](https://user-images.githubusercontent.com/45917984/94311221-e1d85200-ff48-11ea-9696-d0f61af6990f.png)

**Comment by thesublimeobject** [comment]
@hayleyhailstorm hmm this looks like an issue with elementor's implementation of isotope, and not necessarily an issue with isotope itself. if i understand correctly, this isn't an instance of isotope you're initializing yourself, but an instance that's being initialized through the essentials plugin, correct? if that's the case, you may need to contact elementor's support since they will know more about their own implementation. i'd be happy to try and help, but i would likely need some more information.

**Comment by hayleyhailstorm** [comment]
Fair enough. That is correct, I am using Isotope through the Elementor Essential Addons plugin. I will reach out to them, thanks for your assistance!
