### ISSUE TITLE
Issue matching the regular expression with the string in the search bar example.

### ISSUE THREAD

**Issue by Athelstan-no** [metafizzy/isotope#1569]
**Test case:** https://codepen.io/daniel_san_uk/pen/dyXdgjv

I'm trying to change the way the search bar works for my use case.

If you check out the above example and type _Where can I buy_ it will return the correct result. But if you append to that search term and type _Where can I buy from in_ then no results are found because the string no longer matches the regular expression because the characters _space_ and "in" aren't found anywhere in the text of the item.

The code used the .match() method . It's using
<code>var searchResult = qsRegex ? $this.text().match( qsRegex ) : true;</code> and <code> qsRegex = new RegExp( $quicksearch.val(), 'gi' );</code>

I'm kind of new to JavaScript and this has started to go way over my head. You don't need to give me the exact answer, but could you point me in the right direction regarding how I could update this code so that it will match any of the string against any of the regular expressions rather than it being an exact match?

**Comment by thesublimeobject** [comment]
this is really more of a "JS language" question than it is an "isotope library" question/bug/issue. i'll give you some quick direction, but for the future, this really isn't the place to ask questions like this.

off the top of my head, you could do something like this, i suppose—

`let matchMultipleWordsFromSearch = $quicksearch.val().split(' ').join('|')`

this basically just splits the string into words from the spaces, and then re-joins them using the `|` (or) from regex, but to be clear, this will still be a little wobbly since it's just going to match _any_ ONE of the words, which will give you some incorrect results. your regex will need to be a bit more specific/complex.

for example, "where can buy from in" will return only the item you're trying to specify, but "where can i buy from in" will return another as well since it's also matching `i`.

some resources: https://regexr.com/, https://www.xspdf.com/resolution/50661403.html

**Comment by Athelstan-no** [comment]
Thank you! I really appreciate you taking the time to answer this on here. This is indeed the kind of answer I was looking for. I'll try this out and of successful I'll update the use case on codepen so others can check it out.
