### ISSUE TITLE
horizontalOrder, sortBy, imagesLoaded & masonry layout not obeying left-to-right

### ISSUE THREAD

**Issue by zrubinrattet** [metafizzy/isotope#1571]
Test case:
https://codepen.io/hc4zrr324/pen/QWKMKRg

You can see from the numbers in the grid items in the test case that the isotope grid is not obeying `horizontalOrder`. FWIW, this problem also seems to happen if the `getSortData` and `sortBy` keys are omitted from the object passed to the isotope method. This leads me to believe imagesLoaded may be part of the problem but I'm unsure. Any help appreciated. Thanks for the great plugins!

**Comment by thesublimeobject** [comment]
@zrubinrattet —

hey there! thanks for submitting this. i believe this issue comes from the difference in height of the items. for example, in your pen, the reason #4 is sitting in the middle of #5/#6 on the second row is because that the gap has not been filled completely from the first row, so it still things that gap needs to be filled before moving on to the second row. does that make sense?

i know that this isn't the best answer, or really a solution for you, but i do know this is a common issue and one i've had to navigate fixing many times myself. give me a little bit of time and i'll try to get back to you with a better answer/solution. i need to look into a few things.

until then, there are other custom ways around it, but i'm going to try and get back to you hopefully by later tonight, or tomorrow at the latest. thanks for your patience. :)

**Comment by thesublimeobject** [comment]
@zrubinrattet —

my apologies, i clearly should have taken more time to look at the example in the first place. you've actually just made a very small error, so this is quite an easy fix! :)

```
var $grid = $('.grid').imagesLoaded(function(){    
    $grid.isotope({
        itemSelector : '.grid-item',
        percentPosition : true,
        masonry : {
            columnWidth: '.grid-sizer',
            horizontalOrder : true, // moved into 'masonry' options
        },
        getSortData : {
          order : "[data-isotope-order] parseInt"
        },
        sortBy : 'order'
    });
});
```

as you can see from the comment above, all i changed was the location of `horizontalOrder`. you had it in the main isotope options, but this is an option _specific to_ masonry, so you need to add it to the masonry options _specifically_. i changed this in the codepen and after it re-loaded, the orders was indeed correct.

let me know if you have any other issues/questions!
