### ISSUE TITLE
Unable to push grid-items on hover

### ISSUE THREAD

**Issue by mellocodes** [metafizzy/isotope#1572]
Hello!
I'm currently using Isotope for a portfolio gallery w/ filters and it's working pretty well... except when I try to reveal figcaptions underneath a grid-item.
The figcaptions are supposed to appear underneath the grid-item on hover, pushing the grid-items below (in the same column) downwards, by making use of the hovered grid-item's bottom margin. I've been able to pull off this effect no problem working with regular HTML/CSS... but for some reason I've been unable to implement it after installing Isotope.
When I try to push other items down by increasing the grid-item's bottom margin on hover, the figcaptions overlay the grid-item below, and the grid-item's bottom margin slides underneath, instead of properly pushing.

Testcase (forked from the "Fluid Masonry layout" example):
https://codepen.io/mellocodes/pen/dypVpQw

I'd very much appreciate the help!! I'm on the very last stretch of completing my website, and solving this would really make the website *work* visually.

**Comment by thesublimeobject** [comment]
@mellocodes —

isotope uses absolute positioning for the items in the grid, therefore, this same effect cannot be achieved in the same way you describe it above (without isotope).

the reason that, without isotope, the hover pushes the items _down_ is because that items are, by default, positioned relatively to one another unless otherwise specified. since isotope positions items absolutely, each item has no effect on the other items' positioning. 

off the top of my head, i'm not really sure there's going to be a great way to get the _very same effect_ while still using isotope. you would probably need to, instead, have the figcaption overlay the item by transitioning up. for example, i made the following changes to the pen to achieve such an effect—

```
figcaption {
    width: 100%;
    position: absolute;
    bottom: 0;
    left: 0;
    z-index:10;
    opacity: 0;
    transition: all 0.2s ease;
    padding-bottom: 1em;
}

.grid-item:hover figcaption{
    opacity: 1;
    font-size: 22;
    font-weight: 600;
    background-color: yellow;
    transition: all 0.5s ease;
}
```

nonetheless, this is just an example/suggestion. there are other potential solutions, it just depends on what you would like. i hope this helps!
