### ISSUE TITLE
Grid duplication for infinite scolling / fullscreenscroll (vertical & horizontal)

### ISSUE THREAD

**Issue by sbdgithub** [metafizzy/isotope#1573]
Hi, 

i would like to create a grid (eg 30 images) and this grid should be duplicated vertically and horizontally.

Via a viewport (like a mask), I can scroll endlessly through the gallery via drag and drop (fullscreenscroll). 

like this page: https://bien-joue.ca/en/

Is a duplication (same image grid) possible? Any suggestions?

Many Thanks
André

+++

For scrolling I use: https://ilyashubin.github.io/scrollbooster/

+++

A scribble is attached for a better understanding. I hope it's reasonably clear :)

![grid](https://user-images.githubusercontent.com/69640549/104197062-d68c3200-5424-11eb-9234-8855b31e693e.png)

**Comment by thesublimeobject** [comment]
@sbdgithub —

> Is a duplication (same image grid) possible? Any suggestions?

sure, it's definitely _possible_, although i'm honestly not sure isotope would even be your best bet for this. if you were to use it, packery might be a better option simply because you don't really need isotope's sorting/filtering functionality for this at all. you could maybe even use it in conjunction with [infinite scroll](https://infinite-scroll.com/), and just clone your items over and over instead of fetching new items.

that said, you could probably find a slider that would better fit this functionality. for example, you could perhaps use [swiper](https://swiperjs.com/) with slide groups, or something like that. swiper already duplicates the items for you in some circumstances due to wrapping around back to the beginning when the end is reached. and truly, what you're looking to build is really just a page-wide slider with vertical mobility. 

hope those suggestions help. either way, isotope probably isn't the way to go (though i suppose it would be possible).

**Comment by sbdgithub** [comment]
@thesublimeobject 

Thanks! I'll be happy to look at your suggestions! 

All the best
André
