### ISSUE TITLE
Vertical Column Lines

### ISSUE THREAD

**Issue by yash-lturkmen** [metafizzy/isotope#1574]
Sorry for no code adding, but I just want to ask question about "Column Lines" I know that it working item based and not really we have a column. But I want to recognize and create vertical lines to separate columns (on 3-Columns create 2 verticals inside, on 2-column create 1 vertical.)

If someone faced and know, Ill be glad for help. Sorry for no codepen.

**Test case:** https://codepen.io/desandro/pen/mEinp

**Comment by thesublimeobject** [comment]
> If someone faced and know, I'll be glad for help. Sorry for no codepen.
> Test case: https://codepen.io/desandro/pen/mEinp

I'm sorry, but unfortunately there is not enough information provided here for me to sufficiently help you. 

First of all, it does not match the requirements provided in the [contributing guidelines](https://github.com/metafizzy/isotope/blob/1dd4cd186a599dfd70846431506437fe774c285e/.github/contributing.md) (which I'm assuming your read since your link to "Test case" is just a direct copy of the base test case off that page.

Second, I'm not sure what you mean by "Column Lines". As far as I know, "Column Lines" is not a valid parameter. 

I would be happy to help you, but please, first try to solve the issue yourself/construct something small so that I can better understand what you're wanting to achieve.
