### ISSUE TITLE
Bottom corner stamp isn't working

### ISSUE THREAD

**Issue by ianthedev** [metafizzy/isotope#1588]
A demo that was modified from the [official stamp demo](https://isotope.metafizzy.co/options.html#stamp) is linked below. As the demo shows, my project requires the stamp (the dotted-bordered one) to be at the bottom-right corner.

At first, the layout seems okay. But when you resize the window, the column of grid items which is above the stamp starts to move weirdly, snapping to the bottom of the stamp.

**Test case:** https://codepen.io/IanY/pen/LYWYQzd

**Comment by thesublimeobject** [comment]
@ianthedev — [Per the docs](https://isotope.metafizzy.co/options.html#stamp),

> The stamp option stamps elements only when the Isotope instance is first initialized. You can stamp additional elements afterwards with the stamp method.

Therefore, on-resize it seems like you'll need to re-layout the elements using the method, which you should be able to do using a simple re-size listener. I tested this using just this, and it seemed to work better:

```
$isotope = $('.grid').isotope({
  itemSelector: '.grid-item',
  stamp: '.stamp',
  percentPosition: true,
  masonry: {
    gutter: 20,
    horizontalOrder: true
  }
});

window.addEventListener('resize', () => $isotope.isotope( 'stamp', '.stamp' ))
```

But you may need to mess with it a bit to get it more to your liking. In addition, I don't actually think the alignment of the other items is due to the stamp; it seems more like it's related to your setup/styles, so I don't think the two are actually related, but if you continue having issues, you're welcome to ping me back in this thread and I can give it another look!
