### ISSUE TITLE
Unable to use dynamic list on filters

### ISSUE THREAD

**Issue by tjuarez** [metafizzy/isotope#1590]
Hi everyone! Sorry if I not have a test case, but the thing is that I do not know hot to do what I want to do.
I have two filters: Categories and Subcategories.
When I click on a Category I want products to be filtered and also the list of Subcategories updated. Then I want to click on any Subcategory, and have products filtered by that Subcategory.
My english is not really good, so I hope to be clear.
Can anyone guide me on how to implement that behavior?

**Comment by thesublimeobject** [comment]
@tjuarez — Without knowing what kind of menus/structure you're using, it's going to be difficult to help you with this, which is one of the reasons a reduced test case is suggested. In addition, while I am happy to help try and guide you toward an answer, I'm not going to write the entirety of the code for you—that's not really how _issues_ are meant to be used.

That said, the filters themselves should be pretty straightforward using any of the Isotope example on the website. For the categories/subcategories, you could use a simply listener on the regular categories, and just show/hide the subcategories based on which parent category is currently selected.

For example, if you have three parent menu items, you could add an event listener to those parent items, and then add either a class, id, or data-element to each parent item, and when that parent item is active, filter the subcategories by the active parent, using whichever form of identification you would like, in order to show/hide the subcategories. 

I'd be happy to help more if you come up with a working example and you can't get something working.
