### ISSUE TITLE
Sorting/Search with Inclusive and Exclusive Filters

### ISSUE THREAD

**Issue by jessiberu** [metafizzy/isotope#1594]
https://codepen.io/jessieberu/pen/JjWNrbb?editors=1010

I have linked the codepen for my example.

I am trying to create a sorting and filtering memberlist, and would like to be able to have my "Members" section as an exclusive filter, while having all the rest of the filter options being _inclusive_. I also would like for the Search Box to be fully functional, as it currently stops working whenever you click on a sort or filter option.

**Comment by thesublimeobject** [comment]
The Search —

Okay, so the reason that your search does not work, while the example's does, is that in the example, the line of code to actually search the text is `$this.text().match(qsRegex) : true;`, which works because that there is nothing inside the items/elements/divs other than the text string represented and rendered there. On the other hand, your items are filled with several other divs. Since, in this case, `$(this)` refers to the current item, if you use the exact same line of code used in the example, this value will try to match with the text inside the item div, which is just `''` since there isn't any text _directly inside that div_. 

Therefore, you need to instead rewrite that line to properly select the element/s you would like to search, i.e., `$this.find('.shifter').text().match(qsRegex) : true;`. I tried this and it did work. This selects the element with class `shifter` first before grabbing the text, since this is the element with the names inside of it.

The Filters —

You could do this one of several ways. Off the top of my head, I might create an object for the filters like,

```
let filters = {
    member: '',
    otherCategory: [],
    anotherCategory: [],
    ...
}
```

And then write a function to update these such that the member filters simply replace the current selection/string on change, and the rest of the filters concat a new string to the array. You'll need to write another separate function to join the array into one properly formatted string as well. There are a few examples of both of these on the Extras page if you need any guides. 

I can expand on either of these if you have any questions, though!
