### ISSUE TITLE
Vanilla JS filters with toggle + search

### ISSUE THREAD

**Issue by AndyVokurka** [metafizzy/isotope#1598]
Hi, @desandro, do you happen to have a working **Vanilla JS** version of the combination of filtering with toggle buttons with search field? I've been trying to figure it out on my own but that proved to be quite too much.

https://codepen.io/desandro/pen/vEJbNr
https://codepen.io/desandro/pen/mCdbD

**Comment by thesublimeobject** [comment]
@AndyVokurka — 

Hey there. What have you tried so far? It would be easier to help if I had a working example of what you've tried. That said, I can give you a quick overview of what I have written in an older repo that worked for me.

My code is actually wrapped in a class, which made some of this a bit easier for me personally, but I'm sure you could accomplish the same thing functionally, if you wanted to do it that way. 

I have an eventListener registered on the search element:

`this.elements.search.addEventListener('keyup', debounce(this.onKeyUpListener.bind(this), 150))`

And then my eventListener function, `onKeyUpListener` looks like this:

```
onKeyUpListener({ target }) {
    let { value } = target
  
    this.isotope.arrange({
        filter: (item) => item.dataset.title.match(new RegExp( value, 'gi' )),
        ...
    })
    this.isotope.layout()
    ...
}
```

Here, the argument `event` from the listener is automatically passed to `onKeyUpListener`. I have also bound the `this` value from the class to the function in order to access variables I have saved in the class like the Isotope instance for example. So the argument `{ target }` in the function is essentially just `event.target` from the event variable itself, where that target is the current element that the listener is attached to, so the search element in this case. Therefore, the filter function inside of the `isotope.arrange` function takes the value from that target, which would be the current value of the search input element, creates a new `RegExp` from that value, and searches the current Isotope items for elements that match current titles from the datasets I have attached. Of course, you don't have to do it this way. You could do it many other ways as well. For example, more like the jQuery example provided, you could search the text fields of the item instead like so,

`filter: (item) => item.textContent.match(new RegExp( value, 'gi' ))`

or, if you wanted to search an element inside of the item with some other classname, you could do that like this,

`filter: (item) => item.querySelector('classname-of-inner-element').textContent.match(new RegExp( value, 'gi' ))`

I think this should be plenty to get you going in the right direction, but please feel free to follow this up with any additional questions and I can point you in the right direction. That said, any further questions dealing with smaller issues that are more specific to the instance you are trying to create should be sent along with a Codepen [per the contributing guidelines](https://github.com/metafizzy/isotope/blob/1dd4cd186a599dfd70846431506437fe774c285e/.github/contributing.md)—it will be difficult for me to help you debug anything more particular without an example. The code here is just to get your started since you didn't send an example along, but I think this should be a solid start for ya :).
