### ISSUE TITLE
isotope + infinityscroll (json) + lightgallery js is'nt working

### ISSUE THREAD

**Issue by sakearzoo** [metafizzy/isotope#1601]
I am trying to use isotope & infinityscroll v4 with lightgallery js . using json data

As lightgallery js isnt working i tried to append via

$grid.on( 'append.infiniteScroll', function( event, response, path, items ) {
$( items ).find('.my-dev-id').lightGallery();

but that also doesnt working.

any suggesation would be helpful

**Comment by thesublimeobject** [comment]
Hey @sakearzoo, I would be happy to try and help you, but please provide a reduced test case per the [contributing guidelines](https://github.com/metafizzy/isotope/blob/1dd4cd186a599dfd70846431506437fe774c285e/.github/contributing.md). Unfortunately, I cannot provide much help without more details.

**Comment by sakearzoo** [comment]
@thesublimeobject https://codepen.io/bebeba2841/pen/GRmpZmL this is the temporary codepen of my code . in js there is a function lightGallery(document.getElementById('gallery') , {})  . i am unable to make it work with the lightGallery function. i have tried to initialize but still didnt work for me.

**Comment by thesublimeobject** [comment]
@sakearzoo — Well, if your issue is with lightGallery and not with Isotope, then this really isn't the right place to raise an issue (the issue would be with lightGallery, not Isotope, so you should really ask it there, instead).

That said, I'll try and point you in the right direction. Just taking a quick look at your code, you are selecting an element for lightGallery using `document.getElementById()` and all of your `#gallery` elements have the same elementId, which is invalid HTML. In order to fix this, you should use a `querySelector` or `getElementsByClassName` or a jQuery selector. Having multiple elements with the same Id is likely part of the reason there's an issue. 

Beyond that, I couldn't really say for sure why it's not working, since I'm not super familiar with the lightGallery plugin. If you continue to have issues with it, I would perhaps raise an issue over there as suggested above, but if you have any other issues with Isotope in particular, I would be happy to try and help you out!
