### ISSUE TITLE
Vertical layout with relative or static placement

### ISSUE THREAD

**Issue by 1000camels** [metafizzy/isotope#1602]
I am trying to understand how I can use Isotope just for filtering a vertical list, without requiring the setting of absolute placement and a top and left size. I have managed to override them a little, but they still seem to be applied and then reset, so I get a jarring effect.

**Comment by thesublimeobject** [comment]
@1000camels — That is the way the library is written, so unfortunately I cannot really provide any solid assistance here. In order to truly change the manner in which the items are positioned, you would essentially have to rewrite the entire library, which you are welcome to do, but it's just not something that falls within the scope of these issues. Sorry I can't be of more help. If you would like to follow up with some more specific questions, I might be able to point you in the right direction.
