### ISSUE TITLE
ISOTOPE - 2 grid in one page

### ISSUE THREAD

**Issue by tcosteur** [metafizzy/isotope#1604]
Hello, 

I am trying to implement 2 different isotope grids filter + pagination on one page and have issues setting up the second one. 
As you can see on my pen, the first one is working and not the second one. I used the same id and class for both grid and think the issue is there but I couldn't manage to update my javascript to make it work!
Could someone help me with that?

Thanks

https://codepen.io/tcosteur/pen/oNWoNWP

**Comment by thesublimeobject** [comment]
- @tcosteur -- i'm on mobile right now and the pen won't load for me, but strictly based on what you've said, i can tell you that your issue is using the same id for both grids. that's invalid html, and likely creates and invalid isotope instance as well (although i can't confirm this off the top of my head). change your second id and either register them with the same class for two with the same settings or two different instances if the settings are different. 

if you have any more issues with that, just follow up here.
