### ISSUE TITLE
2 different layouts on one page?

### ISSUE THREAD

**Issue by ThePixelPixie** [metafizzy/isotope#1605]
I've got things working pretty well, except that the 2nd layout doesn't start out expanded. You can see in the linked Codepen. When you click on the "list view" button on the right, the table layout has everything on top of itself. How can I make sure it starts out with the first category already expanded into the table?

[https://codepen.io/ThePixelPixie/pen/MWmVLzP](url)

I also just added the filter options, but can't figure out why sort is working fine, but filter is not. Any insight would be greatly appreciated.

Thanks so much in advance.

**Comment by thesublimeobject** [comment]
@ThePixelPixie — could you please re-post the link? it currently just goes to a blank isotope issues url.

**Comment by ThePixelPixie** [comment]
Yes. Not sure why it attached that weird URL. Here's the correct one: https://codepen.io/ThePixelPixie/pen/MWmVLzP

**Comment by thesublimeobject** [comment]
@ThePixelPixie — Sorry for the delay getting back to you on this. Nonetheless, I think this should be an easy fix. 

I just moved the initialization of each Isotope instance to the top for reference. Then, inside of the layout switch function wrapper, I added a little conditional where, if the selected instance was `#div2`, it triggered the layout function, like `$table.isotope('layout')`. I think your issue is just that when the function switches the layout, it `show()`s the other isotope grid, but it hasn't really been fully initialized, so running the `layout()` method on the grid will fix that. Let me know if you have any other questions!
