### ISSUE TITLE
Weird shifting in different browser sizes

### ISSUE THREAD

**Issue by wes-p** [metafizzy/isotope#1608]
Hi all,

I am taking over a website from someone else and haven't worked with isotope so far, so i am quite lost as to where to begin.
The problem here is that the grid sometimes seemingly randomly appears as one column less than the layout the items are scaled for.
So even though everything is set up for a 4-column layout (items are 25% width and so on) they are displayed in 3 columns and left-aligned.
![image](https://user-images.githubusercontent.com/61241931/134490773-c6f122e2-3c4a-443c-996f-f0343a08a668.png)

Using Chrome this issue appears at (one of many sizes) 1314px browser width, but 1313 and 1315 are fine again, it's really weird.

Live: [enorm.digital](https://enorm.digital)

Any help or ideas as to what to do here are really appreciated!

**Comment by thesublimeobject** [comment]
@wes-p — Hey there! Happy to try and help you out here. I took a quick look, and it does seem like that would be expected behavior, but it really just depends on what the code looks like and what your intentions are. There are a number of reasons this could be happening (both on purpose and on accident), so I would need to see more of the code that's currently there, along with your intentions for column sizes on different browser/device sizes.

Once you send that over, it should be pretty easy to figure out from there! :)
