### ISSUE TITLE
Initialize in HTML and filter dynamically

### ISSUE THREAD

**Issue by TOPDSGN** [metafizzy/isotope#1610]
How can I filter dynamically the results, sorting, adding or removing items… if I initialize Isotope via HTML attribute?

`<div class="grid" data-isotope='{ "itemSelector": ".grid-item", "layoutMode": "fitRows" }'> `

Thanks in advance!

**Comment by thesublimeobject** [comment]
@TOPDSGN — To be honest, I've never used Isotope via the HTML attributes, since it always seemed like a convenient way for a very simple grid/filter setup, but not of much use beyond that. Unless there's some reason you really _need_ to do it that way, I would just suggest writing it via JS the normal way. Off the top of my head, I can't really think of a way to dynamically sort/filter/add/remove without doing that anyway. The adding/removing would need some JS on its own anyway, so I would probably just go that route.

Let me know if you have any further questions and I can try to help push you in the right direction! :)

**Comment by TOPDSGN** [comment]
@thesublimeobject Thank you for your reply. Currently a dozen grids on different pages, all with different configurations and layout modes, but with a similar structure. That's why I think it's best to initialize each grid using HTML with its different settings, and use a single JS function to manipulate them, since the different filters and orders would be the same. But once they initialize in HTML, I don't know how I can manipulate them with jQuery. Any idea about the right way is welcome and very grateful!

**Comment by TOPDSGN** [comment]
I thought this way it could work, but it seems not :( 

```
<div id="mygrid" class="grid" data-isotope='{ "itemSelector": ".grid-item", "layoutMode": "fitRows" }'>

$('#mygrid').isotope({ filter: '.myfilter' });
```

**Comment by thesublimeobject** [comment]
@TOPDSGN — 

Actually, let me clarify something: when you say 

> sorting, adding or removing items

do you mean dynamically adding and removing items from the set of filterable items, or do you just mean in the sense that they are naturally filtered. I thought you meant dynamically adding/remove new items to the set of filterable items, but if you just mean it in the sense of normal filtering, that's different.

**Comment by TOPDSGN** [comment]
@thesublimeobject I need to add and remove elements dynamically

```
$('#mygrid').isotope( 'insert', elements )
$('#mygrid').isotope( 'remove', elements )
```

But I also need to filter and sort

```
$('#mygrid').isotope({ filter: '.selector' });
$('#mygrid').isotope({ sortBy : 'random' });
```

**Comment by thesublimeobject** [comment]
@TOPDSGN — Okay, yeah, that's what I originally thought, but just wanted to check in case I misunderstood. In that case then, yes, I would absolutely go with regular JS code. The HTML entities are more of a shortcut, and you're not going to get the depth of functionality that you need from it; i.e., there's no way to insert/remove elements, mutate other settings, etc. 

I would imagine that you could potentially get it working by initializing it with the HTML entities, if you really want to do it that way, I'm just not sure it would be of any benefit to you, since you're going to have to write some custom JS anyway. I always thought of the HTML entities as a way to quick-initialize for very simple grids that don't need other support code, if that makes sense.
