### ISSUE TITLE
Quicksearch stops working after resetting filters

### ISSUE THREAD

**Issue by gracehcoote** [metafizzy/isotope#1615]
**Reduced test case**
https://codepen.io/gracehcoote-the-decoder/pen/pormZOp

**Issue**
I am using inclusive checkbox filters alongside the Quicksearch feature to filter a collection of events. All works fine, except that after clearing filters the Quicksearch feature no longer works. I have not been able to find this specific case mentioned elsewhere. Test case linked above uses the Inclusive Checkboxes example from Isotope docs. I have added in the search bar and a Clear Filters button, along with the code to make those work. Again, search code is based off the example in this Pen: https://codepen.io/desandro/pen/wfaGu

My own code is very simple, and uses a combination of basic jQuery and sample code found online to reset the filters, uncheck checkboxes and clear the search bar:

```
$('#clear-filters').click(function() {
  $($container).isotope({
    filter: '*'
  });
  $('.quicksearch').val('');
  $('.quicksearch').keyup();
  $('input[type="checkbox"]').prop('checked', false);
});
```

Having tested it, the thing that causes the search bar to stop working is the ```filter: '*'``` - once that is removed, it works. But I obviously need this to reset everything and can find no other way to do so. All other filters still work after reset, the only thing not working is the Quicksearch. 

You can replicate the bug by using the search bar first (to show it works), then use the Clear Filters button and try again. You will see it no longer works.

Thanks in advice for any help offered!

**Comment by thesublimeobject** [comment]
@gracehcoote — Sorry for the delay here; have you figured this out yet?

Thank you so much for all of the information. It was super helpful. This was really a great test case.

I think the issue is that you are resetting the Isotope filter function/functionality by re-calling it inside both the clear filters block as well as the checkboxes block. 

For the clear filters functionality, I think you could re-write it like this —

```
$('#clear-filters').click(function() {
  $('.quicksearch').val('');
  $('.quicksearch').keyup();
  $('input[type="checkbox"]').prop('checked', false);
  $container.isotope('layout');
});
```

You might still need to clear the active filters, but either way, you probably shouldn't reset the filter function. Just arrange/layout without changing it by changing the variables that are being filtered. 

For the checkboxes block, you're doing the same thing which is resetting the filter function, I think. So you might need to reconfigure that block as well. Honestly, I haven't used the jQuery version of Isotope in years so most of my experience is with the vanilla JS version, so I could be slightly off on some of my assumptions here. Either way, it might actually be easier to switch over to vanilla JS for this. 

That said, rewriting that checkbox block could be time consuming. I would suggest maybe looking at some of the other examples that might help out with that, and if you can't figure it out, maybe ping me back and I can try to help out some more. 

Also, just thinking through this abstractly, if there's a way you could re-assign the filter functionality by using some sort of saved variable/object, that might work too. For example, 

```
let settings = {
  itemSelector:  '.item',
  filter: () => qsRegex ? $(this).text().match( qsRegex ) : true,
}
```

And if you want to filter specifically by a checkbox value, do it sort of like you are now, but then anytime someone starts typing in the input box, re-initialize the Isotope search settings by doing something like, 

`$container.isotope(settings)`

I think this would also work, but again, just ping me here if you have any follow up questions.

**Comment by gracehcoote** [comment]
Hi @thesublimeobject, thanks so much for getting back to me and for taking the time for this. Unfortunately I haven't had a chance to look at this problem any further than I already did as the project is on such a tight deadline, so I just hoped someone might be able to help me out! Which you so kindly have :)

The way the filters are working is slightly different now, they are no longer inclusive filters, but it doesn't have any real impact on this problem or for the purposes of testing for it. I did however notice that the ```filter: '*'``` element isn't actually what's causing the problem after all, which is odd because I did test for that. It just seems instead that any changing of the filters was causing the quicksearch to stop working.

In any case, I have made some changes as you suggested, but still not quite there. You can see that now the search is now trying to function after filters are cleared, in that the items are rearranging, so this is a step in the right direction. But the search itself isn't finding anything now, it returns zero results each time you try.

I have updated and saved the Codepen as best I could based on your advice but I'm obviously missing something, which is probably an obvious thing!

You can see the code for yourself by visiting the same Codepen link as before, but here's what I've changed mostly:

```
var settings = {
  itemSelector: '.item',
  layoutMode: 'fitRows',
  filter: () => qsRegex ? $(this).text().match( qsRegex ) : true,
}

// init Isotope
var $container = $('#container').isotope(settings);

// use value of search field to filter
var $quicksearch = $('.quicksearch').keyup( debounce( function() {
  qsRegex = new RegExp( $quicksearch.val(), 'gi' );
  $container.isotope(settings);
}, 200 ) );
```

**Comment by thesublimeobject** [comment]
@gracehcoote — This is my fault...I quickly wrote that function without thinking about the context of `this`. It should be like this: 

```
var settings = {
  itemSelector: '.item',
  layoutMode: 'fitRows',
  filter: function() { 
    return qsRegex ? $(this).text().match( qsRegex ) : true
  },
}
```

I changed it to this in the pen and then tested it, and it did seem to work correctly now. Let me know if you don't have similar results!

**Comment by gracehcoote** [comment]
@thesublimeobject Yep you are completely correct, it works perfectly now! I can't think you enough, this has been really bothering me as the last thing I just couldn't fix! Thank you so much

**Comment by thesublimeobject** [comment]
@gracehcoote — So glad I could help! Your issue description made it very easy to help. Happy to assist you anytime :)
