### ISSUE TITLE
Add class to hidden items

### ISSUE THREAD

**Issue by michael-oxborrow** [metafizzy/isotope#1619]
Rather than hidden items receiving a style of display none could we instead add a class of hidden?
How could I achieve this, please?
I'm using vanilla javascript rather than jQuery

**Comment by thesublimeobject** [comment]
@michael-oxborrow — Have you tried using the `removeComplete` event/listener? This might work since it passes the removed items, and you could probably swap out the `.hidden` class and remove the `display: none`, but I would have to try it out. This is just my first instinct. 

If you put together a working demo let me know and I can help some more. Thanks!
