### ISSUE TITLE
How to toggle all / group - while using filters.

### ISSUE THREAD

**Issue by fasteddys** [metafizzy/isotope#1622]
Hello I can toggle individual items.

But `when filters are applied, I am not sure how to toggle all items in a group/row or col,` how to retain the filter state, i.e. not loose the user selected filters and layout. 

Can you please give me some guidance on using the `filters and toggle all in a combination`.

**Comment by thesublimeobject** [comment]
@fasteddys — I'm sorry, but you're really going to need to be more detailed in your description of what exactly you're looking for. I'm just not completely sure what you mean with regard to filters/toggle in combination. In addition, [per the contributing guidelines](https://github.com/metafizzy/isotope/blob/1dd4cd186a599dfd70846431506437fe774c285e/.github/contributing.md), could you please provide a working CodePen, or something of the sort, showing what you have attempted so that I can see what you need help with. Thanks!

**Comment by fasteddys** [comment]
In the original version they had a `t0ggle all`, by size and relayout called, i dont see that functionality in this verison

**Comment by thesublimeobject** [comment]
@fasteddys — Again, I would be happy to help you, but please reference the contributing guidelines I posted before. IN order to help, I really need a reduced test case so that I can see what you're trying to do. Otherwise it's going to be difficult for me to intuit what you need. Thanks.
