### ISSUE TITLE
Callback function does not work at all

### ISSUE THREAD

**Issue by rl55** [metafizzy/isotope#609]
I've just spent nearly 8 hours on callback functions only to realise that they don't work at all in the version 2. Could you kindly check and confirm.

**Comment by fmalina** [comment]
How exactly is one supposed to rerun isotope when elements in the container are updated e.g. via `$container.html(new_list)`?

**Comment by desandro** [comment]
@fmalina `reloadItems` http://isotope.metafizzy.co/methods.html#reloaditems

**Comment by fmalina** [comment]
I added `$('.js-listings').isotope('reloadItems');` to my ajax success. It causes all elements to stack up in the top left corner, because they have no left and top, just `style="position:absolute;"`.

Calling isotope again `$('.js-listings').isotope('reloadItems').isotope();` will add the `left` and `right`, but then animation disperses items from that corner, which doesn't look right.

The solution seems to be `$('.js-listings').isotope('destroy').isotope();`.

**Comment by GreatPotato** [comment]
I have an issue where "layoutComplete" does not fire if there are no items in my container.

My use case:

1) Initialize Isotope on an empty container
2) After initialization is complete, load items in the container via AJAX

Is there a way to check if initialization of isotope is complete?
