### ISSUE TITLE
Double animation after update from v1

### ISSUE THREAD

**Issue by wschwaiger** [metafizzy/isotope#660]
Hi,

I have a problem after updating from v1. Please see under http://launch.qualitywork.at/kuro.qualitywork.at/ the double animation. The code that I am using can be found under http://launch.qualitywork.at/kuro.qualitywork.at/files/kuro.qualitywork.at/assets/qualitywork.js

Many thanks for your help.

Best,
Wolfgang

**Comment by ronjb04** [comment]
I have the same issue. and i tried what is suggested above however issue still remains.

however the issue doesn't happen immediately, it only happens after a couple of filtering.
it looks like it breaks the function since i notice that on filtering the css (transition settings) are injected to the .grid-item and then it is removed after the transition(animation is done). where the only injected css that remains are supposed to be the (position:absolute; left: 0; top:0;)

however after filtering multiple times, and the double animation is happening i notice that the transition css are not being removed anymore. these css now and forever remains inline in the .grid-item

    transition-property: opacity, transform;
    transition-duration: 0.4s;
    transition-delay: 0ms;

here's a video so you can see what i mean.
https://drive.google.com/file/d/1dHQNs9V-aWHsynlHMDNtH5w-OZ0w2DhR/view?usp=sharing

**Comment by ronjb04** [comment]
additional info: this only happens on angular SSR build, while im on development this issue doesn't happen. I have tried different layout modes however the issue remains. So i think it has something to do with ssr or dist build.

**Comment by Xteda87** [comment]
Hi. 

> additional info: this only happens on angular SSR build, while im on development this issue doesn't happen. I have tried different layout modes however the issue remains. So i think it has something to do with ssr or dist build.

I have the same issue. Did you find solution?

**Comment by Xteda87** [comment]
> additional info: this only happens on angular SSR build, while im on development this issue doesn't happen. I have tried different layout modes however the issue remains. So i think it has something to do with ssr or dist build.

@ronjb04, I have the same issue. Did you find solution?

**Comment by ronjb04** [comment]
> > additional info: this only happens on angular SSR build, while im on development this issue doesn't happen. I have tried different layout modes however the issue remains. So i think it has something to do with ssr or dist build.
> 
> @ronjb04, I have the same issue. Did you find solution?

no buddy, as for now the only solution i did just to get things functional is to remove the animation since i don't have much time to dig further.. Good luck! i hope you can sort it out

**Comment by noah2233** [comment]
I have the same problem with angular when I run build with the prod flag
