### ISSUE TITLE
categoryRows

### ISSUE THREAD

**Issue by koyllis** [metafizzy/isotope#676]
Is there any categoryRows layout similar to v1 ?

**Comment by MikeWilkie** [comment]
+1 This is the sole reason we are sticking with v1.

**Comment by benjamincharity** [comment]
:+1:

**Comment by kenricf** [comment]
:+1:

**Comment by fnagel** [comment]
+1

**Comment by BrunoSpy** [comment]
:+1:

**Comment by rucativava** [comment]
I just discovered I need categoryRows ... I switched to v2 because I had to use the sort function which was not working with v1. Should I go back to v1? It is a pity categoryRows is not an option in v2...

**Comment by adispezio** [comment]
+1!

**Comment by inluxc** [comment]
+1

**Comment by pabloalbizu** [comment]
+1

**Comment by pkundrat** [comment]
Hi. Here is the working categoryRows for v2. At the moment i am a bit overwhelmed with work to do proper code submit including working codepen - hopefully in a few weeks. By then you can use this.
[categoryRows-v2.js.txt](https://github.com/metafizzy/isotope/files/623232/categoryRows-v2.js.txt)

**Comment by ses2013** [comment]
Hi there
wanted to ask what happend to this project.
Would still be vey usefull to have. 
Without any instructions I couldn't use the layoutmode.
Thanks

**Comment by Singleshutter** [comment]
Is it possible to define the Category for this on the fly?

**Comment by Singleshutter** [comment]
Is it possible to have Multiple SortBy with Category Rows?

**Comment by desandro** [comment]
It's time to close this issue.

Isotope v1 had a broader layout mode API. Layout modes could make multiple passes over items in order to produce more complex layouts. For example, with categoryRows, the layout mode would iterate over all the items, placing each into a category, then iterate over all the items again so each category would get proper spacing.

Starting in Isotope v2, the layout API was integrated closer with Isotope's layout behavior. In doing so, the ability for multiple passes & measuring was lost. Layout modes like categoryRows were lost, but other layout modes were better focused.

If you are interested in re-writing the categoryRows layout behavior, you'll have to build a new layout library on top of [Outlayer](https://github.com/metafizzy/outlayer), just like Isotope, Packery & Masonry. It certainly can be done. I am leaving that to you.

I'm sorry to decline this feature request. But by saying no here, I can keep Isotope a little cleaner everywhere else. It's a common trade-off I have to consider when maintaining years-old popular project like Isotope.

Thanks all for your feedback. If you do make a new version of categoryRows, please follow up on this thread. 🌈🐻

**Comment by anoosurf** [comment]
oh this was one of the most useful layouts we used ... is it still possible in v3 using your categoryRows-v2.js.txt code you suggested ?
