### ISSUE TITLE
Fitrow layout align to bottom 

### ISSUE THREAD

**Issue by ashangtr** [metafizzy/isotope#687]
Hi 
i would like to know is there any possible way to align fitrow layout divs to bottom, here i attached sample image please check.

Thank you
![untitled-2](https://cloud.githubusercontent.com/assets/7380849/2773996/473134d8-caac-11e3-8752-5289d1bd45a8.jpg)

**Comment by aaronhudon** [comment]
Here's a hack to the _layoutItems routine that bottom aligns.  This assumes you're using 'FitRows'.
Perhaps this can be integrated properly into the code?  I just needed it to work locally...  

```javascript
/**
 * layout items
 * @param {Array} items
 * @param {Boolean} isInstant
 */
Outlayer.prototype._layoutItems = function( items, isInstant ) {
  var _this = this;
  function onItemsLayout() {
    _this.emitEvent( 'layoutComplete', [ _this, items ] );
  }

  if ( !items || !items.length ) {
    // no items, emit event with empty array
    onItemsLayout();
    return;
  }

  // emit layoutComplete when done
  this._itemsOn( items, 'layout', onItemsLayout );

  var queue = [];

  for ( var i=0, len = items.length; i < len; i++ ) {
    var item = items[i];
    // get x/y object from method
    var position = this._getItemLayoutPosition( item );
    // enqueue
    position.item = item;
    position.isInstant = isInstant || item.isLayoutInstant;
    queue.push( position );
  }
  
  //BEGIN HACKED ROUTINE TO BOTTOM ALIGN 'FIT ROWS'
  //aaron hudon:
  // post process the queue to bottom align each item
	var workingY = 0;
	var maxHeightForY = -1;
	for(var idxItem = 0; idxItem < queue.length; idxItem++) {
		if( queue[idxItem].y == workingY ) {
			maxHeightForY = Math.max(maxHeightForY, queue[idxItem].item.size.innerHeight);
		}
		if ( queue[idxItem].y != workingY || idxItem == (queue.length-1)) {
			// moving to the next Y (row) or on the last row.  fix up the height of this and the other items on the same Y
			for (var i = idxItem-1; i >= 0; i--) {
	
				// since we're working backwards, stop processing when we've hit an item on a different row (y)
				if ( queue[i].y != workingY ) break;
				
				var shiftAmount = maxHeightForY - queue[i].item.size.innerHeight;				
				if(shiftAmount > 0) {
					queue[i].y += shiftAmount;
				}
			}
			maxHeightForY = queue[idxItem].item.size.innerHeight;
			workingY = queue[idxItem].y;
		}
	}
// END HACKED ROUTINE TO BOTTOM ALIGN 'FIT ROWS'

  this._processLayoutQueue( queue );
};
```

**Comment by desandro** [comment]
@aaronhudon Thanks for taking a shot at this. As you have discovered, there's no easy way to do this. Isotope's API has been optimized for algorithms that only iterate over items once. Ideally, there's be a hook so you could iterate over items and then do follow-up logic to actually set their position.

That said, I cannot recommend this hack. It is changing the `Outlayer` code, which isn't a good place for this since it's specific to the `fitRows` layout mode for Isotope.

I'm still considering adding more logic to handle these kind of layout algorithm features

**Comment by aaronhudon** [comment]
Agreed.  If we could have a callback that would provide all the items *before* they are changed in the document then the implementing callback could be free to tweak the x,y values as needed.

**Comment by zaccety** [comment]
Er, this is ironic, my layout is doing exactly this, but I don't want it to be... I haven't worked out why yet, have used Isotope elsewhere before without issue, any ideas gratefully received...

![ethical-tea-partnership-media-centre](https://cloud.githubusercontent.com/assets/608956/7185498/d914b10e-e45a-11e4-9da5-a1d1152830ee.png)

**Comment by geekosophe** [comment]
+1 It would be awesome !

**Comment by richgcook** [comment]
+1

**Comment by QuentinBMAS** [comment]
+1

**Comment by QuentinDallaserra** [comment]
and for good luck +1

**Comment by QuentinDallaserra** [comment]
@aaronhudon thanks, I'll be using your hack.

**Comment by desandro** [comment]
It's time to close this issue. Copying over https://github.com/metafizzy/isotope/issues/676#issuecomment-317074148

Isotope v1 had a broader layout mode API. Layout modes could make multiple passes over items in order to produce more complex layouts. For example, with categoryRows, the layout mode would iterate over all the items, placing each into a category, then iterate over all the items again so each category would get proper spacing.

Starting in Isotope v2, the layout API was integrated closer with Isotope's layout behavior. In doing so, the ability for multiple passes & measuring was lost. Layout modes like categoryRows were lost, but other layout modes were better focused.

If you are interested in creating this layout behavior, you'll have to hack it yourself. Perhaps building upon @aaronhudon's code. It certainly can be done. I am leaving that to you.

I'm sorry to decline this feature request. But by saying no here, I can keep Isotope a little cleaner everywhere else. It's a common trade-off I have to consider when maintaining years-old popular project like Isotope.

Thanks all for your feedback. If you do create a solution, please follow up on this thread. 🌈🐻
