### ISSUE TITLE
Isotope filter/sort from paginated data - lazy load vs infinite scroll

### ISSUE THREAD

**Issue by igregson** [metafizzy/isotope#724]
@desandro There's a message in [this Stack Overflow question](http://stackoverflow.com/questions/11841150/infinite-scroll-with-isotope-and-filtering-in-wordpress) linking to a now 404 page related to you saying that lazy loading was a better approach than infinite scrolling for cleaner integration with Isotope. 

Question: Does this still hold true for Isotope v2?

Also, if I might make a feature request:
How about a v2 tutorial of Isotope with infinite scroll / lazy load (whichever you suggest, or perhaps both) that includes filtering and sorting?

**Comment by webeditors** [comment]
Pagination + Filtering don't necessarily conflict. To give you a scenario, user has a database of hundreds of products which are available in various colours and sizes. An initial view of all (unfiltered) products would produce a very long page - precisely where pagination comes in. However, in your Amazon-style margin you have filters for colours and sizes. Currently there's no way of combining the two (since traditionally you'd leave the pagination to server side and isotope needs all the data client side). However, if Isotope could handle both filtering and pagination (i.e., 'only show items 1-10 of the 24 found in the filter), that would be a better solution.

**Comment by igregson** [comment]
Just learned that Mixitup has a pagination extension ([info/demo here](https://mixitup.kunkalabs.com/extensions/pagination/)). 

I'd love to be able to achieve something similar with Isotope, especially since Isotope doesn't need jQuery. 

@desandro and others, any thoughts on this?

**Comment by rctneil** [comment]
Are there any more updates in this line of discussion?

I'm thinking about moving my sites list of content over to use Isotope for sorting and filtering but with 600+ items that each need to show a photo and text based details for each it is a lot all at once. I would love to be able to either add some pagination or infinite scroll pagination to help but it would need to integrate into Isotope somehow I imagine.

**Comment by AladinWay** [comment]
Any news about how to combine filtering, sorting and pagination ?

**Comment by desandro** [comment]
I still have the same position. Filtering and pagination do not make a good user experience. Pagination could be achieved by Isotope as a new feature. I don't feel there's enough interest yet for this feature.

**Comment by igregson** [comment]
@desandro Care to share more on how you'd suggest achieving a masonry layout with a large data set that needs to be filter/sort-able *without* adding pagination to something like Isotope? 

Thoughts on starting a "+1 :+1:" thread to get a sense of the interest/demand in an Isotope pagination feature?

**Comment by helenemartin** [comment]
" Filtering and pagination  do not make good user experience" How do you know? Facts? Studies reflecting this statement?
I have been struggling with Isotope and filtering for a while so a little help would be beneficial
+1 
Thank you in advance

**Comment by Oshuma** [comment]
"I still feel that filtering and sorting and infinite scroll is not a good user experience."

Twitter, Facebook, and Instagram use infinite scroll (read: hidden pagination).

lol I'm done, bruh

**Comment by downFast** [comment]
"Twitter, Facebook, and Instagram use infinite scroll " @desandro said WITH filtering is not a good experience, he never said infinite scrolling isn't. And I agree with him, because if you have 20 items but you only load 10 before you start scrolling, if you start filtering, you may not find any filtered items with your 10 loaded item which means that you have 0 results unless you scroll.

Basically you go to a page, you filter, no results found, you should tell the users: "hey, no filtered items found, maybe you could try to scroll and load more items"

That's bad experience indeed.

**Comment by bussemac** [comment]
I am very interested in adding paging; our initial load is currently 156 items, each with an image and text, so the page is huge and painful to load. The server-side data is easily cached so providing it to Isotope all up front is fine, I just want the front-end to be a little cleaner.

**Comment by centrual** [comment]
Maybe virtual layout is better solution for this topic.
All items( maybe millions of data ) loads on js array and then isotope displays only visible area items.

**Comment by 10SexyApples** [comment]
+1 for hidden pagination of isotope returned items ... I'm building a one page vertical timeline of filterable events so, like others, have a large/heavy data set to sort ... and it's just no good to make folks have to reload the page for each filter ... isotope type functionality for filtering/sorting is a must ... also +1'ed the spinealign/timeline be updated for v3 as this would obviously be perfect for my needs ;-)

**Comment by archifox89** [comment]
Im interested in having pagination work with isotope, please consider building this feature.

**Comment by vcernomschi** [comment]
I am also interested in having pagination+filtering with isotope effects.

**Comment by Terrycy** [comment]
I think there is a way to do it out of the box, this may seem convoluted at times so bare with me!

The background as to why I think it can be done:
In our solution we have 220 items in a list, the items can be filtered by type, due and a category. The type can have multiple values selected to display only the things you're interested in.
When a new item comes into the page (via SignalR) we use iso.insertItems to add it and render the appropriate filter on the page if it doesn't exists in type, else increase the count for the filter type.

Each of these filters has it's own function by the relevant name. Instead of Isotope filtering by it's default filter option, there is a single function that iterates through an object literal, if the item to be filtered matches a function in the object, it will run that function else it will filter it in the normal way.
```
function () {
                var isMatched = true;
                var value = '';
                for (var prop in todo.todoSort.filters) {
                    var filter = todo.todoSort.filters[prop];
                    // use function if it matches
                    filter = todo.todoSort.filterFns[filter] || filter;

                    // test each filter
                    if (filter) {
                        isMatched = isMatched && $(this).is(filter);
                    }
                    // break if not matched
                    if (!isMatched) {
                        break;
                    }
                }
                return isMatched;
            }
```

Without going too much into filter groups, you end up filtering from an object, based on the example I gave in the opening paragraph:

```
{due: "7", cat: "urgent", type: ".diary, .post, .table"}
```
Where due, cat and type are a property in todo.todoSort.filters and the filter is their values.

This group of filters would return a list of all items that are urgent, due in the next 7 days and are diary, post or table entries.
Within each filter function, we have another one that controls the count of each visible item per type, so in a list of 220 items, we end up with a user able to see that they have x number of diary, post and table items that are due in 7 days and are urgent.

This is an example of one such function, it tests the item and returns is visible, true or false

```
                 todoDueslider: function () {
                     var todoSort = todo.todoSort;
                     var number = $(this).find('.sort-by-duedate').text();
                     var matchBool = parseInt(number) <= todoSort.filterVals['todoDueslider'];
                     switch (todoSort.filterVals['todoDueslider']) {
                         case 7:
                             matchBool = $(this).hasClass('ShowFor7');
                             break;
                         case 14:
                             matchBool = $(this).hasClass('ShowFor14');
                             break;
                         case 28:
                             matchBool = $(this).hasClass('ShowFor28');
                             break;
                         default:
                             matchBool = $(this).hasClass('ShowFor7');
                             break;
                     }
                     todoSort.visibleCount($(this).attr('id'), matchBool);
                     return matchBool;
                 },
```

Where  todoSort.visibleCount($(this).attr('id'), matchBool); takes the current item being iterated over and updates the count if it is visible.

Hopefully you're still with me!
We can use this logic to create pagination on the fly. Within the visibleCount function, we create an object of all current visible items on the page but while we iterate through them, we can create a counter, when the counter is divisible by (e.g.) 20, we insert page 2 and append items into that part and so on resulting in an object that would look like this:
```
pageObject = {
    0: [item1, item3. item10, ...], // 20 items 
    1: [item42, item46, item50...], // and so on
}
```
Finally we iterate through this object, something like:

```
var $buttonContainer = $('#pagination-container");
$buttonContainer.html(''); // clear the pagination container
for (var page in pageObject) {
    var buttonHtml = '<a href="#" class="paging" data-filter=".page-'+page+'">'+page+1+'</a>;
    //  add the button to the container
    $(buttonContainer).append(buttonHtml);
    for(var item in page){
        // give each item the page class to be filtered on
        $(page[item]).addClass('page-'+page);
    }
}
```
We would need to add a click event to the buttons using `$('body').on('click', '.paging',function(){...});` as the button doesn't exist on page load. The function would use the data-filter-group set on the `#pagination-container` of paging and the data-filter of the page number (this example is code we use for type but slimmed down) :
```
            var $this = $(btn);
            // set filter group
            var filterGroup = $this.parents('#pagination-container').data('filter-group');
            // create array of current filters
            var currentFilter = (!$this.hasClass('active')) ? [$this.data('filter')] : [];

            this.sortFilters[filterGroup] = currentFilter ;
```
and then run the filters using `iso.arrange({ filter: this.options.filter });`

In theory all we have to do is have a default paging to page 0 in our filter group 

```
{due: "7", cat: "urgent", type: ".diary, .post, .table", page:"0"}
```
When you click a page, the page filtergroup will change to the relevant button and only elements that are on page-x will be shown!

**Comment by danielfriis** [comment]
+1

**Comment by twanbraas** [comment]
+1

**Comment by cam-vanorman** [comment]
+1

**Comment by robfaas** [comment]
+1

**Comment by majtymit** [comment]
+1

**Comment by dave4jr** [comment]
+1

**Comment by adisaf** [comment]
+1

**Comment by amydws** [comment]
This is a really common request by my agency and designer clients so I think there is a demand for it. When I see it in a design I'm like noooooo, please not again.

**Comment by daslicht** [comment]
+1

**Comment by shampliu** [comment]
+1

**Comment by LichtAnd** [comment]
+1

**Comment by mgrn0** [comment]
+1

**Comment by davekeehn** [comment]
+1

**Comment by vallabhvrao** [comment]
+1

**Comment by dylanfpaul** [comment]
+1

**Comment by robfaas** [comment]
@desandro quite a lot of plusses, indicating there is a lot of interest...

**Comment by lukeaus** [comment]
+1

**Comment by desandro** [comment]
**Please do not add a +1. Please add a 👍  reaction to one of the top two comments.** You can choose to subscribe if you additional notifications. +1 comments ping everyone already subscribed but provide little value.

**Comment by Siilionu** [comment]
We need pagination+filtering.

**Comment by thesublimeobject** [comment]
I think that @desandro is correct in asserting that filtering/sorting + pagination/infinite scroll is not necessarily a good user experience, and further, would be extremely complex to build given the amount of options that compound on one another in a situation like this. 

For example, if you have filtering/sorting + pagination/scroll, when you sort/filter does it sort/filter all the items, or just the items currently showing? If it only sorts those on the current page, why have pagination or why have filtering? They're both doing the same thing to some extent. On the other hand, if it does then sort everything, the pagination becomes immediately null to an extent, or at least confusing from that point on from the user's perspective. So, in this case, the initial state of the items is more of a *state* than it is anything else. 

I have fairly strong opinions on this only because I think there are better ways to do it in most cases; although I understand there are cases with extremely large numbers of items where you need something built around that specific experience. But this is why I _don't_ think this functionality should be part of Isotope. 

That said, I have built several instances with both simple filters and multiple intersecting filters with lazy-loading, load more buttons, and pagination (combinations of different kinds). I am happy to provide extensively detailed examples of one or two of these and post them to a public repo if people are interested. But I want to be clear that implementing these has everything to do with using Isotope as a library _to your advantage_ based on the wealth of information each instance in itself exposes. Isotope provides the tools to implement anything like this if you use it correctly (aside from whether the UI/UX of such an implementation is good or bad).

**Comment by Siilionu** [comment]
How about page loading speed? For example, if page contains 200+ images, then it takes forever to load. To avoid this, lazy load/load more/pagination would be helpful. There are many sites that use Isatope + lazy load/load more/pagination and no one will complain about the bad experiences. How do they do it?

**Comment by thesublimeobject** [comment]
@Siilionu 

> although I understand there are cases with extremely large numbers of items where you need something built around that specific experience. 

I agree, as you can see from above, that there are, at times, situations which, depending on the design, in some way necessitate adding some of this functionality. Also as I said above, if there is enough interest I will make anywhere from one to multiple examples.

**Comment by Siilionu** [comment]
Thanks. Working examples would be welcome. :)

**Comment by Nick-Fiasco** [comment]
@desandro Would be very interested in this, or at least a good method of infinite scroll/load more pagination that keeps the combination filters in place for appended items. 

Anyone got a good resource for making this work?

**Comment by thesublimeobject** [comment]
@Nick-Fiasco Can you clarify in more detail what you mean by "keeps the combination filters in place for appended items"?

**Comment by Nick-Fiasco** [comment]
Sure thing. 

I have three combination filters working with isotope to filter a lot of products (approx 200 items)

On page load I'm only loading in the first 16, and currently have an Ajax load more button setup to bring in more products and append them into the isotope.

When this happens however the current filters I have chosen do not apply to the newly appended products. I need these newly appended products to match the currently chosen filters, or for the isotope to re-layout with the filters so that I am not just grabbing all products of any kind.

Does that make more sense? 

Thanks for the help.

**Comment by thesublimeobject** [comment]
@Nick-Fiasco That does make sense. 

(a) There really does seem to be a need for an example here, so I will try to make an extremely comprehensive one, but given how busy I am with work right now, I don't know if I'll be able to get to it this weekend, or in two weekends; so as long as everyone is patient, I can eventually get a really nice example written out.

(b) If you want some advice before I finish this example, I'll say this:

Off the top of my head, what I would probably do is set some kind of global state in an object that contains information about your isotope instance. I usually use objects of some sort to track different states that aren't explicitly parts of the Isotope instance. So, with that, you can at least keep track of what the current Isotope filter state is...or I suppose you can grab it from Isotope if you want to run a query every time, but that might be less efficient. 

Next, I would do one of two things:

(1) **Option 1**: Make sure your data structures on the backend are in a state such that each ajax query only returns items that match the current filter; then when the user hits load more, only return the required set of items and append them.

(2) **Option 2**: This is (_vaguely_) what I normally do. When the page loads, load whatever normal amount of items you would like. As soon as your critical items load, run an ajax request to fetch _all the items_; given there won't be images associated with them, this shouldn't take very long. Once the request finishes (I usually use a Promise for this since it makes it easy to handle errors, etc.), store (cache) the items as JSON in window.localStorage. You can do this in numerous ways and categorize them if you would like. Then every time the you hit load more, you can fetch the items from the appropriate categories.

The first time I did this it seemed really complex, but when you break it down into it's component parts, and make sure you're keeping track of state fluently, it's actually a very, very straightforward, functional, and organized way of loading in new items.

@Nick-Fiasco If you have any more specific questions before I can get an example up, let's find a way to chat outside of this thread so that we're not pinging everyone else. :)

**Comment by Nick-Fiasco** [comment]
Thank you so much. Sounds like a great idea @thesublimeobject – Trying to find a way to contact but you don't have no contact details on Github. Is there another channel I can reach you on (without writing email addresses on the thread)

**Comment by IIIu6ko** [comment]
http://codepen.io/Igorxp5/pen/ojJLQE

**Comment by thesublimeobject** [comment]
@Nick-Fiasco Sorry, just seeing this. You're welcome to email me at hunter@wearekbd.com.

**Comment by robfaas** [comment]
@IIIu6ko Great! Seems to do the trick!

**Comment by Siilionu** [comment]
Any progress about Isatope + lazy load/load more/pagination working examples?

**Comment by thesublimeobject** [comment]
@Siilionu Sorry, I have been extraordinarily busy at work over the past few weeks. I can still do this, but out of curiosity, was the example from @IIIu6ko not helpful?

**Comment by Siilionu** [comment]
For me (I'm sure I'm not the only one) would be an ideal solution as follows:

1) "Load More" button is only displayed if the "pages" is more than one.
2) When the last "page" is shown, it will display the text: "_No more items to show_" and then the text disappears after 4-5 seconds. Example: http://vankarwai.com/themes/lobo-agency/
3) It should work with filter and without filter.

Could set:
1) How many items will be displayed before the "Load More" button appears.
2) How many items will be displayed when clicking on the "Load More" button.

Here is the code that I have right now: https://jsfiddle.net/qg6orjnr/20/

Thank you for your help. :)

**Comment by Nick-Fiasco** [comment]
The example from @IIIu6ko was very helpful and nice to see something like this working. 

I still hope to find a solution with combo filters with the lazy load, and then in the end drop this into a Wordpress / PHP site to work with pages of content.

So if possible, I would love to be able to see an example and get some help so that could be used in this way.

**Comment by Siilionu** [comment]
Unfortunately, the example from @IIIu6ko does not work for me. I really don't know what is wrong in this code: https://jsfiddle.net/qg6orjnr/22/  :(

**Comment by Siilionu** [comment]
I tried the example code from @IIIu6ko. Something is still wrong with pagination. If I refresh the page, it shows all items (should show only 10 items). If I resize page, it shows 10 items as it should to show. https://jsfiddle.net/qg6orjnr/25/

**There are some additional questions:**

How to add the active class to isotope pager?
How to add multiple data-filter categories in item?

Thanks. :)

**Comment by IIIu6ko** [comment]
@Siilionu 

> How to disable pagination if only one page is displayed?

```
  // hide isotope-pager if only 1 .pager.
  $('.isotope-filter-links li a').click(function(){
    if ($(".pager").length == 1) {
      $(".isotope-pager").css("display", "none");
    } else {
      $(".isotope-pager").css("display", "block");
    }
  });

  if ($(".pager").length == 1) {
    $(".isotope-pager").css("display", "none");
  } else {
    $(".isotope-pager").css("display", "block");
  }
```
https://jsfiddle.net/qg6orjnr/27/

**Comment by Siilionu** [comment]
Thank you very much @IIIu6ko :) 

But I think it needs some window resize function. If "itemsPerPageDefault" set to more than items.

**Comment by mikeantkowiak** [comment]
Hi guys! 

Is there a way to include multiple data-filter values for the pagination example? Looking at the code it looks for a single data-filter value can be used. 

Is there a way to take IIIu6ko's example https://jsfiddle.net/qg6orjnr/28/ and integrate multiple values for data-filter on each item? Or use that exact example but stick with using the classes instead of the data-filter value.

Any help would be great. Thanks everyone!

**Comment by thesublimeobject** [comment]
@mikeantkowiak I'm honestly not sure what your use case for that would be, and I wonder if you could give an example because I have an inclination there would be a better way to do it. Nonetheless, it should be easy enough to change the filter values in `data-value` from a single string to a comma-delimited pair (or list) of values. Then when selecting the filter in JS, just use something like `data.split(',')` to split the value of the data-filters into an array, and apply that array of values to the filter in whatever way you would like to use it, depending on the use case.

**Comment by mikeantkowiak** [comment]
@thesublimeobject I basically want the exact same thing as https://jsfiddle.net/qg6orjnr/28/, but each item can more then one category/filter associated with it. I want the original functionality of isotope with the ability of multiple class names as filter categoreies values, but integrated into the code on https://jsfiddle.net/qg6orjnr/28/ as it looks like they have removed the normal functionality of how isotope works with class names.

The calls to data-filter values are called within the script multiple times, so getting my head around how that will integrate into the current code is a little confusing. I really just want the normal isotope functionality, with pagination and filtering functionality(each item with multiple filter values).

Would anyone be willing to adjust that code for me? It would be amazing if someone could help out!

Thanks again @thesublimeobject for taking the time to respond to my inquriy.

**Comment by thesublimeobject** [comment]
@mikeantkowiak I'm sorry, I'm not sure I understand what you're trying to describe. At this point, I'm thinking you maybe want each item to have multiple filter values associated with it?—in which case you just need to add more classNames to the item itself. But, I guess you might be saying as well that this would lead to multiple categorical filter options, in which case you need to have an entirely different filter set as well? In that case, this would be more work than just adding classNames, of course. If I'm still not understanding what you're saying, perhaps open a new issue as we seem to be getting a little too granular for everyone in this thread to receive notifications.

**Comment by mikeantkowiak** [comment]
@thesublimeobject  https://jsfiddle.net/qg6orjnr/28/ This code uses the data-filter attribute instead of class names, and only takes one value, compared to the class names where you can have multiple values. I basically want to be able to use multiple values, so that the filtered items can be associated to more than one category(filter value).

I have posted a new ticket here. https://github.com/metafizzy/isotope/issues/1255

Thank you for everyone's help. Hope my other issue clears up what we are looking for!

**Comment by thesublimeobject** [comment]
hey everyone,

so while i have yet to complete the solution to the main problem of the thread (i have been quite busy), i just wanted to share the place where it _will_ be solved. this is a github repo where i am current compiling a library of all the tools i use for/with isotope in order to make websites for my firm: https://github.com/katiebushdesign/isotopes. i am currently about halfway through, but there is a lot more to do. i will be adding the load module to it very soon, so i am hoping to get to the main issue as soon as i can, but it will just depend on how free i am. i am happy to have anyone use components from this, and/or file issues for example or features they would like. i thought it could be helpful especially once i get the load module in there (starting to integrate the first part tonight).

**Comment by Nick-Fiasco** [comment]
Thanks for the update @thesublimeobject and thanks for working on it.

The concept [https://jsfiddle.net/qg6orjnr/28/](https://jsfiddle.net/qg6orjnr/28/) here does a really nice job of filtering and paging, but as @mikeantkowiak mentions is only setup to work with one filter category for each item. I am in the same boat here as I need to use multiple categories per item to filter through. 

I'm also still wondering about how this would work when in a php environment (like Wordpress) where we would be pulling in content/posts etc from the server and how these would be loaded in (before they get paged in isotope) 

Would it still be loading all items on initial page load? Rather than loading the next page of items when you click on the next page/number?

**Comment by thesublimeobject** [comment]
@Nick-Fiasco I mostly work with Wordpress, so my library/example will be specific to your question, actually. In short, I've done it both ways. Sometimes I load an initial set while loading all of the items in the background and storing them in a live array or localStorage, and sometimes I only make a call to load more posts whenever a button of some sort is clicked. It really works just as well either way. I haven't had an issues with either approach.

**Comment by Nick-Fiasco** [comment]
@thesublimeobject that sounds great, but it sounds a little over my level of Javascript knowledge to load a certain number and store things up etc. But that is definitely something I would like to learn and see some example of if possible. 

I have used an Ajax load more button with it, but then didn't know how this would/could work with the paging within isotope.

**Comment by thesublimeobject** [comment]
As @desandro referenced above, I believe this issue is essentially solved by the infinite-scroll plugin. I've used it with Isotope and it works very smoothly. He also has several example to reference in the documentation, but I am happy to help anyone out who needs help setting it up. It took me a few mins to figure out the best way to go about it in Wordpress, so I'm happy to lend a hand, especially in that direction.

**Comment by Nick-Fiasco** [comment]
Thanks @thesublimeobject I have actually been looking into the infinite scroll plugin to use with Isotope. I would definitely be interested in any pointers or best practice with using them together. I did have a brief test of setting it up, but I didn't think my code was very efficient, or at least not as slim as it could be as I'm still learning more about Jquery. I build almost exclusively with Wordpress, so any pointers would be great!

**Comment by Nick-Fiasco** [comment]
Hi @thesublimeobject sure! More help would be great. You can contact me on nick@nickylew.com and we can go through more about this through email. Cheers all!

**Comment by Tinougit** [comment]
Hello guys,

I used IIIu6ko's example (nice job btw!) on my symfony project, but I have a little issue.
When I refresh my page (where filter and pagination are), all my images are displaying (I set my limit to 6), but as soon I click on a filter button or page 2  (pagination not disappear), for exemple, everything returns to normal.

HTML and "data attr" seem ok: https://pasteboard.co/GHUUZRo.png

I guess this is a priority loading problem with JQuery, here's the script (I removed ImageLoad lib because I didn't need it): 
https://jsfiddle.net/ansj6vzs/

Let me know if more code is needed.

If someone could help me,

Thanks !

**Comment by srikat** [comment]
@Tinougit It can be fixed like this: https://jsfiddle.net/acr8pk01/1/

**Comment by desandro** [comment]
I'm re-posting my comment from https://github.com/metafizzy/infinite-scroll/issues/674#issuecomment-311658109

---

**Can you use Infinite Scroll with Isotope's filtering and sorting?** Yes. The code would look something like:

``` js
// init Isotope
var $grid = $('.grid').isotope({
  // Isotope options
});

// init Infinite Scroll
$grid.infiniteScroll({
  // Infinite Scroll options
  // do not set append
  // do not set outlayer
});

// append items on load
$grid.on( 'load.infiniteScroll', function( event, response, path ) {
  var $items = $( response ).find('.grid-item');
  // append items after images loaded
  $items.imagesLoaded( function() {
    $grid.append( $items );
    $grid.isotope( 'insert', $items );
  });
});
```

**Add a 👍  reaction** to this issue if you would like to see this feature added to the docs with demos. Do not add +1 comments — [They will be deleted](http://metafizzy.co/blog/use-github-reactions-delete-plus-1-comments/).

---

But I still feel the same: **Infinite Scroll with Isotope's filtering and sorting is not a good user experience**. I've discussed this elsewhere in metafizzy/isotope#724.

**Infinite Scroll and filtering/sorting have conflicting behaviors.** Infinite Scroll adds more items in sequential order. Filtering removes items. Sorting re-arranges the order of item. This leads to several odd behaviors:

+ If there is a filter applied, should Infinite Scroll keep adding items even though most added items may be hidden?
+ When you add items via Infinite Scroll, should the sort order be used against all the items as a whole, or just the new set of items?
+ After filtering, if there scroll area has decreased, should Infinite Scroll add more items?
+ After filtering and infinite-scrolling more items, there might be only 20 items shown, but 200 items added to the Isotope instance. The user could be bombarded with way more items than they expected. What happens to their scroll position?

I could go on. My point is that just because even though you can use these features together, maybe you should not. Then again, metafizzy/isotope#724 has gotten a lot of 👍  so maybe I should sit back and just let this ride.

**Comment by Tinougit** [comment]
@srikat Thank you, it's working !

**Comment by desandro** [comment]
This issue thread has grown unwieldy and long to load. Now that Infinite Scroll v3 is out, Isotope & Masonry have direct interoperability, so the nature of this issue has changed.

I'm closing this issue here and re-starting a fresh issue #1358 to better measure current interest. 

---

This original issue also dealt with lazy-loading, a separate issue. Please open a new issue if you are having trouble with lazy-loading.
