### ISSUE TITLE
Fading in each image as it loads...

### ISSUE THREAD

**Issue by eayres** [metafizzy/isotope#727]
Hi!

So I have isotope working beautifully on a website I'm developing. I currently have this working just fine:

$('#thumb-list').imagesLoaded( function() {
$('#thumb-list').isotope({
  // options
  itemSelector: '.itemThumb',
  masonry: {
  columnWidth: 300,
  gutter: 10
}

},
    $('.thumbLoad').animate({opacity:1}, 500)
    );
});

This does a quick fade in of my items all at once after the images have all loaded. However, what I _really_ want is to fade in each image as it's actually loaded individually, perhaps even with a loading gif until the image shows, but I could probably figure that out if I could just get the individual fade ins to work.

Can someone point me in the right direction?

Thanks!

**Comment by macsupport** [comment]
The example shows how to do this with dynamically generated ".items", which I understand (here is my [codepen](http://codepen.io/macsupport/pen/VYjqWL) using velocity.js to load items rather than css3 animation). I seem to be brain dead as to how to implement this with a standard isotope layout, i.e., with ".items" already present in the container.

**Comment by desandro** [comment]
@macsupport If you're using another library for reveal animation, then you should not use `appended`, which has its own `reveal` animation built in. Instead, Isotope needs to add items to the container, and then lay them out. See http://codepen.io/desandro/pen/QwYBQW

``` js
var items = iso.addItems( $item );
// true flag disable layout transition
iso.layoutItems( items, true );
```

Take a look at how [`appended` works](https://github.com/metafizzy/outlayer/blob/v1.3.0/outlayer.js#L729) for details.

**Comment by downFast** [comment]
Hey @desandro you actually did it again, and totally surprised me! I was actually trying to achieve that different fade in effects but using css3, and there you are! Quick question, if I had to adapt your code:

function getItem() {
  var width = randomInt( 150, 400 );
  var height = randomInt( 150, 250 );
  var item = '<div class="item">'+
    '<img src="http://lorempixel.com/' + 
      width + '/' + height + '/nature" /></div>';
  return item;
}

How about simply apply that fade effects to my items rather than creating new ones as you do?

**Comment by eayres** [comment]
Hi all,

This is how I ended up doing it... worked like a charm. Start with opacity
0 in css for your images the somewhere call (obviously changing your
selectors to match your own)-- this worked for me because i'm loading
smallish jpgs that will most definitely be ready to view-- might now work
if you have large file sizes since it assumes the image is good to go:

$('#thumb-list').find('.itemThumb').each(function(i) {
                jQuery(this).delay(i*300).animate({
                    'opacity' : 1,
                }, 800, 'easeOutExpo', function() {
                    jQuery(this).addClass('thumbLoaded');
                });
            });
});

.......................
EMILY AYRES
Photo Retouching + Web & Graphic Design + Web Development + Social Media

**Comment by macsupport** [comment]
Thanks for your update of my little experiment using Isotope and velocityjs!

**Comment by downFast** [comment]
I had a play with velocity and fade images one by one, since @desandro example was working with a button to load the images, I needed to do it so that it worked on load rather. here it is my code pen: http://codepen.io/anon/pen/EarJpd

**Comment by macsupport** [comment]
For anyone interested, here is a simpified update of my isotope/velocity.js codepen with items not created dynamically. (If stagger is set to false, all images load at once with the effect.)

[Codepen Example](http://codepen.io/macsupport/pen/MYLdmZ)
