### ISSUE TITLE
A way to style items in "checkers-board" style

### ISSUE THREAD

**Issue by mogadanez** [metafizzy/isotope#758]
nth-styles is not works in case of sorting, filtering and  even numbers of columns.

Will be good to have classes like odd/even

**Comment by ckarpinski** [comment]
This adds the class "odd" to every other item in a filtered group but it doesnt seem to ever remove the class "odd" - so in my instance after i have clicked all the filter buttons the class odd is on items from all categories not just the currently filtered category. 

Is there a way to remove the class odd from all the other items when you click a new filter button? OR to remove the class odd when the "all" filter button is clicked?

Im trying to use the class to remove style that works when the grid is in "All" showing form but once items are filtered that style messes up the layout so I want to undo it. But since the class "odd" never gets removed completely when i click back to the "all" filter the layout is not back to the original view.
