### ISSUE TITLE
Transition Performance

### ISSUE THREAD

**Issue by marcobiedermann** [metafizzy/isotope#847]
Please do not animate the layout with position `left` and `top`. Can you change it to `translate3d()`?! Animating other properties besides `opacity` and `transform` causes a lot of paint

**Comment by desandro** [comment]
Isotope does [transition with `translate3d()`](https://github.com/metafizzy/outlayer/blob/v1.3.0/item.js#L192-L196). After the transition is complete,  it re-sets layout values to use `left` and `top`, as this provides better interoperability with other libraries, like tooltips and hover cards.

It may be worth considering setting position to 2d transform, rather than `left` and `top`, so not to re-trigger paint. I'll think on this.

**Comment by marcobiedermann** [comment]
Yeah great! :)

**Comment by mathiasrando** [comment]
That would be really great. It take that many items to choke up older smartphones(e.g. iPhone 4S).

**Comment by san** [comment]
Any updates on this?
I am using Isotope with about 200+ items and it's choking even the newest mobile devices.

**Comment by desandro** [comment]
I'm closing this feature request as its been quiet for over a year. I appreciate your feedback, but I've decided to pursue other features and issues for Isotope.
