### ISSUE TITLE
Can't add custom width.

### ISSUE THREAD

**Issue by thehung2224** [metafizzy/isotope#862]
I'm trying to add width to the `<div>` but it doesn't work although I can use filter function. 

```html
<section id="portfolio">
	<div class="container">
		<div class="row">
			<div class="col-md-12">
				<div id="portfolio-filters" class="portfolio-filters">
					<a class="active" data-filter="*">All</a>
					<a data-filter=".web-design">Web Design</a>
					<a data-filter=".logo">Logo</a>
					<a data-filter=".photo">Photo</a>
				</div>	<!-- end portfolio-filters -->
			</div>
		</div>	<!-- end row -->
	</div>	<!-- end container -->

	<div id="portfolio-grid" class="portfolio-grid">
		<div class="portfolio-item photo web-design">
			<div class="portfolio-item__image">
				<img class="img-responsive" src="images/portfolio-1.jpg" alt="Portfolio">
			</div>	<!-- end portfolio-item__image -->
		</div>	<!-- end portfo -->

		<div class="portfolio-item photo logo">
			<div class="portfolio-item__image">
				<img class="img-responsive" src="images/portfolio-2.jpg" alt="Portfolio">
			</div>	<!-- end portfolio-item__image -->
		</div>	<!-- end portfo -->

		<div class="portfolio-item logo">
			<div class="portfolio-item__image">
				<img class="img-responsive" src="images/portfolio-3.jpg" alt="Portfolio">
			</div>	<!-- end portfolio-item__image -->
		</div>	<!-- end portfo -->

		<div class="portfolio-item logo web-design">
			<div class="portfolio-item__image">
				<img class="img-responsive" src="images/portfolio-4.jpg" alt="Portfolio">
			</div>	<!-- end portfolio-item__image -->
		</div>	<!-- end portfo -->

		<div class="portfolio-item logo">
			<div class="portfolio-item__image">
				<img class="img-responsive" src="images/portfolio-4.jpg" alt="Portfolio">
			</div>	<!-- end portfolio-item__image -->
		</div>	<!-- end portfo -->
	</div>	<!-- end portfolio-grid -->
</section>	<!-- end portfolio -->
```

```javascript
jQuery(document).ready(function(){
    
    "use strict";
    
	var container = $('#portfolio-grid');	
	container.isotope({
		// animationEngine : 'best-available',
		animationOptions: {
			duration: 200,
			queue: false
		},
		layoutMode: 'fitRows'
	});	
	
	// filter items when filter link is clicked
	jQuery('#portfolio-filters a').click(function(){
		jQuery('#portfolio-filters a').removeClass('active');
		jQuery(this).addClass('active');
		var selector = jQuery(this).attr('data-filter');
		container.isotope({ filter: selector });
		loadProjects();		
		return false;
	});
	
	function splitColumns() { 
		var winWidth = jQuery(window).width(), 
			columnNumb = 1;
		if (winWidth > 1200) { columnNumb = 5; }
        else if (winWidth > 900) { columnNumb = 4; }
        else if (winWidth > 600) { columnNumb = 3; }
        else if (winWidth > 300) { columnNumb = 1; }
		return columnNumb;
	}		
	
	function setColumns() { 
		var winWidth = jQuery(window).width(), 
			columnNumb = splitColumns(), 
			postWidth = Math.floor(winWidth / columnNumb);
		
		container.find('.portolio-item').each(function () { 
			jQuery(this).css( { width : postWidth + 'px' });
			console.log("test");
		});
	}
			
	function loadProjects() { 
		setColumns();
		container.isotope('layout');
	}			
	
	function loadIsotope(){
	   container.imagesLoaded(function () {
           loadProjects();
       });
	   loadProjects();
	}
    
    loadIsotope();
});
```

Thanks for the great plugin :)

**Comment by downFast** [comment]
You are using isotope v1. you should use isotope v2. In v2 you have element-sizer, which is your element that defines the columnWidth. in v2 you don't need anymore all of that animation option as it uses css3 animation no more jquery. You are using bootstrap, no need of all that if windowWidth stuff, you should read my answer on this stack overflow, read it carefully has it has lots to tell you and to help for your specific case => http://tinyurl.com/lpzfr39

For anything else: http://isotope.metafizzy.co/

**Comment by thehung2224** [comment]
Hi @downFast Thank you for replying.

This code that I have seen from another template, and the bootstrap is using for filter links only. Can you help me edit this code to make it work in V2, I read your answer but I don't understand completely.

**Comment by downFast** [comment]
what do you mean it is using it for filter only?

**Comment by thehung2224** [comment]
I mean the bootstrap used to put filter links (such as: All, Web design,...) only.

**Comment by downFast** [comment]
You should use bootstrap to build ALL your html not use it only for a bit. if you do so then do as that stack answer. In that answer there is:

1: responsive isotope using bootstrap
2: using isotope packery layout mode instead of masonry so that you can have a grid with no gaps
3: combo filters if you want to combo filter like for "Web AND Graphics" categories
4: be able to use combo filter and has history, which changes your www address when you filter so that you can link to a filtered page

On that answer there are all the links which you can click to see what it talks about with example.

**Comment by thehung2224** [comment]
Thank you for useful advices. But I think sometimes (as my case) you need build full-width grid so Bootstrap can't handle that, then you have to define own column width and make it work in responsive mode.

**Comment by downFast** [comment]
That's not correct, bootstrap has container-fluid which makes it full width. The you use your col. classes to define your columns, in the example of that stack overflow, if instead of 
<div class=container">
  <div class="row"> 

You'd do

<div class=container-fluid">
  <div class="row">

Then you'll have a full screen grid. That example it is from a project I am working on which is:

1: full width
2: different item sizes
3: responsive
4: multi filter (combo as described)
5: no gaps (remember that masonry will eventually create some gaps with the grid, that's why you use packer layout mode.

All the isotope links for what I am talking about are in that stackoverflow answer. While in regards of bootstrap full width go check => http://getbootstrap.com/css/#overview-mobile

**Comment by downFast** [comment]
That's not correct, bootstrap has container-fluid which makes it full width. The you use your col. classes to define your columns, in the example of that stack overflow, if instead of 
<div class=container">
  <div class="row"> 

You'd do

<div class=container-fluid">
  <div class="row">

Then you'll have a full screen grid. That example it is from a project I am working on which is:

1: full width
2: different item sizes
3: responsive
4: multi filter (combo as described)
5: no gaps (remember that masonry will eventually create some gaps with the grid, that's why you use packer layout mode.

All the isotope links for what I am talking about are in that stackoverflow answer. While in regards of bootstrap full width go check => http://getbootstrap.com/css/#overview-mobile

**Comment by desandro** [comment]
@downFast Thank you so much for help with this issue. Please email me yo@metafizzy.co so I can send some goodies as a proper thank you.

**Comment by downFast** [comment]
Yo @desandro

**Comment by thehung2224** [comment]
Thank @downFast so so much. I fixed my issue now, the element-sizing tip is used with column classes is really nice. I just improve a little bit that column classes in element-sizing must as same as item column classes or it will won't properly (If it incorrect, please let me know).

Instead of

```html
  <div class=container">
      <div class="row"> 
          <div id="isotope-grid">
             <div class="grid-sizer col-sm-2 col-md-4"></div>
                <div class="item col-xs-12 col-sm-8 col-md-8 loadedItem">
                ....
                ....
```

You'd do

```html
  <div class=container">
      <div class="row"> 
          <div id="isotope-grid">
             <div class="grid-sizer col-sm-8 col-md-8"></div>
                <div class="item col-xs-12 col-sm-8 col-md-8 loadedItem">
                ....
                ....
```

**Comment by downFast** [comment]
The element-sizing is what defines your column and it needs to be either the same of a multiple of what you use for your actual items. Why in my example the grid-sizer had different values even tho they are multiples? because I had different items sizes, big and normal to have a more dynamic grid with element with diff sizes.

**Comment by thehung2224** [comment]
Thank @downFast I understand now. Thank you so much :)

**Comment by downFast** [comment]
You are welcome, remember to use packery layoutMode and all bits and pieces I suggest in that stack answer i linked above. But really, you shouldn't thank me but @desandro and buy him few beers here http://isotope.metafizzy.co/license.html

**Comment by desandro** [comment]
Closing as resolved

@downFast Again, thank you for your help here. I'd really like to get in touch yo@metafizzy.co
