### ISSUE TITLE
Items grouped in slider

### ISSUE THREAD

**Issue by Benboe** [metafizzy/isotope#867]
Hi there,

I was wondering if the following is possible with isotope:

- Say I have a slider (with wordpress posts), every slide has 6 posts
- the posts have categories & tags
- I'd like to click on a category, so all the posts get filtered.. 

If all the posts wouldnt be in a slider, and all on the same "page", it wouldn't at all be an issue of course.. But I was wondering if it's possible with isotope, to do the filtering, so the amount of slides get recalculated & rendered again?

at the moment I'm not using isotope, because i think it isn't possible..  can anyone point me in the right direction?

thanks in advance
Ben

**Comment by desandro** [comment]
I do not recommend using Isotope within a slider. This would be mixing two UI patterns, which can be confusing. You'll have to add additional logic so that slider recognizes which slides are visible, and what order they are in. This can be done with [`.filteredItems`](http://isotope.metafizzy.co/faq.html#filtered-items). I'll leave it up to you to create a solution.
