### ISSUE TITLE
Stray "slide-in" animation occuring after every filter and resize animations

### ISSUE THREAD

**Issue by jtholla2** [metafizzy/isotope#869]
I am having trouble getting isotope to behave correctly with it's animations. It seems to run a slide animation after each animation that is run correctly. I have created a [Fiddle](http://jsfiddle.net/jtholla2/nV5H7/3/) that shows the problem. I'm stumped! Thanks for your help!

**Comment by desandro** [comment]
See http://jsfiddle.net/nV5H7/7/. A couple things fixed:

**1** Remove the old `isotope` and `isotope-item` classes and CSS. These were used in Isotope v1, but are no longer needed. The CSS transition properties are what were causing the double transitions. I replaced `itemSelector: '.isotope-item'` with `.grid-item`.

**2** Simplify the filter logic to just

``` js
$(".grid-controls li a").click(function () {
    $container.isotope({
        filter: $(this).attr("data-filter")
    });
});
```

That `token` and `hasClass` code was not necessary.

**3** set `transitionDuration: '750ms'`, instead of the number `750`. [`transitionDuration`](http://isotope.metafizzy.co/options.html#transitionduration) needs to be set as a string.
