### ISSUE TITLE
append + filter will show a flicker upon the 1st item

### ISSUE THREAD

**Issue by Vivi-wu** [metafizzy/isotope#883]
Hello,

I want to implement lazy load with filter options in my page. Every thing is fine. 
The undesirable thing is that if you set filter options before loading more items, every time adding new items will show a flicker upon the first item.

jQuery version: 1.10.2
isotope version: v2.1.1
browsers: Firefox, Chrome, Safari, Mobile Safari
I provide a test case in fiddle: http://jsfiddle.net/Xue_WU/r8u6ok6h/

Thank you for your help!

**Comment by desandro** [comment]
Hi! Thanks for reporting this issue. This is actually how the insert method is designed to work. I felt that displaying that newly added items with hiding transition, shows users that items are being added. Otherwise, a user could add a set of items, all of which are filtered out, and there would be no visual change.
