### ISSUE TITLE
Layout bug - tiles shoot outwards

### ISSUE THREAD

**Issue by super-cache-money** [metafizzy/isotope#898]
As an example, watch what happens when calling `container.shuffle()` in [this little clip](https://vid.me/OljE).

What tends to cause this behaviour? How can it be avoided?

**Comment by desandro** [comment]
Looks like you have a second transition happening. This is likely caused by `transition: all` CSS set on your item. You can resolve this by setting `transition:` to just the property you need to change, like `opacity`, or remove it completely. Or you can create a second element that does your transition, rather than the item element.

**Comment by super-cache-money** [comment]
@desandro I've scoured my css, and there certainly aren't any `all` transitions...

Any other leads?

**Comment by desandro** [comment]
Could you provide a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
