### ISSUE TITLE
Multiple filters, variable sizes, gets pushed to one column.

### ISSUE THREAD

**Issue by ethanclevenger91** [metafizzy/isotope#922]
http://codepen.io/ethanclevenger91/pen/bdwOWj

I know there's a lot of HTML markup - I pared it down quite a bit, let me know if I need to do more.

There are elements with a width of 24.5% seperated by headers with a width of 100%. Click "Filter1" to filter to just "Hot Bars" items. Then click "Filter2" to filter to both "Hot Bars" and "Soup Fixtures" items. Notice the items are fixed to one column. If you check out the JS pane and uncomment the filter reset to '*' in the `click2` function and repeat the process, the issue should resolve.

Thoughts?

**Comment by desandro** [comment]
Thanks for the demo! I believe the issue is that `columnWidth: '.product:not(.product-seperator)'` will not work for element sizing. Isotope does not support jQuery-like selectors with `:not`. Instead, I recommend you use a proxy sizing element. Yes, it requires an extra tag in the markup, but it will resolve this issue. See demo:  http://codepen.io/desandro/pen/NqbrKr I also changed the horizontal padding: `.product-grid { padding: 5px 0 0 0.08%; }`
