### ISSUE TITLE
CSS transitions in container element along isotope transition

### ISSUE THREAD

**Issue by SergiArias** [metafizzy/isotope#965]
Hi! Thank you very much for your amazing work!

If the isotope item resizes and has CSS transitions, isotope calculates the positions before the transition is completed, as is logical, but gives weird visual behaviour. 

```
.main .post {
        width: (depends on mediaqueries);
        @include transition(200ms ease-in-out 0s);
}
```

And initialization is the easiest possible:

```
var $isocontainer=$('.main');

$isocontainer.isotope({
  // options
  itemSelector: '.main .post'
  });
```

Is there a workaround? Maybe introducing a delay before relayout or including the animation inside the initialization somehow.

**Comment by desandro** [comment]
Thanks for reporting this issue. For transition item content, I recommend creating a separate element, like `post-content` so that the content transition does not conflict Isotope transitions.

If you provide a **reduced test case**, I can provide an example. See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/isotope/blob/master/CONTRIBUTING.mdown#submitting-issues).
