### ISSUE TITLE
Sort top 10 - sort before filtering?

### ISSUE THREAD

**Issue by hagcin** [metafizzy/isotope#973]
isotope will filter the results first and then sort what it filters. It would be better if it sorted results and then filtered the sorted results.

Use case: get top X results after a sort. 

``` js
$grid.isotope({sortBy: 'rating'}); //puts everting in correct order
$grid.isotope({sortBy: 'rating', filter: function() {
      return $(this).index() < 10; // totally ignores order when filtering.
}});
```

isotope currently will: 
The filter will grab the first 10 elements, and sort them by rating. This creates a sorting of only the first 10 elements not the whole set of data. It would be much more helpful if it sorted all the items, and then returned the first 10. (at least in my use case :-) I wonder if it is the way it is now for performance reasons. (sorting the smallest set possible), or is a bug?

is the hide() function the best way to limit result where order of the whole set is important?

**Comment by desandro** [comment]
I'm sorry to see you're having trouble with Isotope.

Filtering by `.index()` will not work because Isotope does not re-order elements in the DOM. This helps performance.

So you want to sort by rating, then show only the top 10. We could hack it by making two `.isotope()` calls. To get the first 10, we need some internal Isotope code to check if this element is one of the first `filteredItem`. Check out the demo: http://codepen.io/desandro/pen/bVbKKW

``` js
$grid.isotope({ sortBy: sortValue });
// filter after sorting
$grid.isotope({ filter: function() {
  // sort if item
  var item = iso.getItem( this );
  var index = iso.filteredItems.indexOf( item );
  return index < 10;
} });
```

**Comment by hagcin** [comment]
That worked Amazing!  Thanks for the quick response. My company is going to be an isotope supporter very shortly. Thanks again.
